// The dictionaries and the lookup, free of React and of the database so the
// printable documents can be built and tested outside the app.

import type { Lang } from "../../../packages/shared/src/format.ts";
import { mondayOf, parseDay, addDays } from "../../../packages/shared/src/format.ts";

type Dict = Record<string, string>;

const es: Dict = {
  // Navigation / tabs
  "nav.home": "Inicio",
  "nav.workers": "Recolectores",
  "nav.crops": "Cultivos",
  "nav.pickup": "Recolección",
  "nav.reports": "Reportes",
  "nav.settings": "Ajustes",
  "nav.back": "Atrás",
  "stack.newWorker": "Nuevo recolector",
  "stack.newCrop": "Nuevo cultivo",
  "stack.registerPickup": "Registrar recolección",

  // Home
  "home.totalHarvested": "Total recolectado",
  "home.pickupsCount": "{n} recolecciones",
  "home.today": "Hoy",
  "home.thisWeek": "Esta semana",
  "home.registerPickup": "Registrar recolección",
  "home.recentActivity": "Actividad reciente",
  "home.noPickups": "Aún no hay recolecciones. Toca “Registrar recolección”.",

  // Shared labels
  "label.workers": "Recolectores",
  "label.crops": "Cultivos",
  "label.pickups": "Recolecciones",

  // People
  "people.empty": "Aún no hay recolectores. Toca + para agregar.",
  "people.tag": "placa",

  // PeopleAdd
  "peopleAdd.gallery": "Galería",
  "peopleAdd.camera": "Cámara",
  "peopleAdd.removePhoto": "Quitar foto",
  "peopleAdd.firstName": "Nombre *",
  "peopleAdd.lastName": "Apellido",
  "peopleAdd.docType": "Tipo de documento",
  "peopleAdd.docId": "Número de documento",
  "peopleAdd.rfid": "Placa / tarjeta RFID",
  "peopleAdd.rfidHelp": "La placa identifica al recolector en la báscula.",
  "peopleAdd.save": "Guardar recolector",

  // Crops
  "crops.empty": "Aún no hay cultivos. Toca + para agregar.",

  // CropAdd
  "cropAdd.type": "Tipo de cultivo *",
  "cropAdd.measuredIn": "Se mide en {unit} · {yield}",
  "cropAdd.lotName": "Nombre del lote *",
  "cropAdd.lotPlaceholder": "p.ej. {label} lote 1",
  "cropAdd.variety": "Variedad",
  "cropAdd.area": "Área sembrada (ha)",
  "cropAdd.save": "Guardar cultivo",

  // RegisterPickup
  "pickup.worker": "Recolector",
  "pickup.crop": "Cultivo",
  "pickup.noWorkers": "No hay recolectores — agrega uno primero.",
  "pickup.noCrops": "No hay cultivos — agrega uno primero.",
  "pickup.weight": "Peso ({unit})",
  "pickup.save": "Guardar recolección",
  "pickup.saved": "✅ Recolección guardada",

  // Reports
  "reports.total": "Total {unit}",
  "reports.pickups": "Recolecciones",
  "reports.toPay": "A pagar",
  "reports.pickers": "Recolectores",
  "reports.week": "Semana",
  "reports.worker": "Recolector",
  "reports.crop": "Cultivo",
  "reports.byWeek": "Recolección por semana",
  "reports.byWorker": "Recolección por recolector",
  "reports.byCrop": "Recolección por cultivo",
  "reports.unitsCollected": "{unit} recolectados",
  "reports.noPickups": "Aún no hay recolecciones registradas.",
  "reports.recent": "Recolecciones recientes",
  "reports.nothing": "Nada aún.",

  // Settings
  "settings.cropTypeTitle": "Tipo de cultivo",
  "settings.cropTypeSub": "Elige uno para cargar sus unidades por defecto",
  "settings.unitsTitle": "Unidades y costo",
  "settings.cropName": "Nombre del cultivo",
  "settings.unit": "Unidad de medida",
  "settings.unitPlaceholder": "kg, racimo, tonelada…",
  "settings.yieldUnit": "Unidad de rendimiento",
  "settings.generalCost": "Costo general por {unit}",
  "settings.generalCostHelp":
    "Este costo aplica a todas las semanas salvo que lo sobrescribas abajo.",
  "settings.saveConfig": "Guardar configuración",
  "settings.weekCostsTitle": "Costos por semana",
  "settings.weekCostsSub": "Sobrescribe el costo por unidad en semanas concretas",
  "settings.noWeeks": "Aún no hay recolecciones registradas para asignar costos por semana.",
  "settings.week": "Semana",
  "settings.costPer": "Costo por {unit}",
  "settings.add": "Añadir",
  "settings.demoTitle": "Datos de demostración",
  "settings.demoSub": "Recolectores, cultivos y 4 semanas de recolecciones",
  "settings.loadDemo": "Cargar demo",
  "settings.clearAll": "Borrar todo",
  "settings.wipeTitle": "Esto borra la temporada",
  "settings.wipeClearBody":
    "Se borran recolectores, lotes, pesadas, liquidaciones y movimientos de esta finca. No hay copia de seguridad y no se puede deshacer.",
  "settings.wipeSeedBody":
    "Cargar la demo borra primero todo lo real: recolectores, lotes, pesadas, liquidaciones y movimientos. No hay copia de seguridad y no se puede deshacer.",
  "settings.wipeConfirm": "Escribe {name} para confirmar",
  "settings.wipeField": "Nombre de la finca",
  "settings.wipeCancel": "Cancelar",
  "settings.wipeMismatch": "El nombre no coincide",
  "settings.languageTitle": "Idioma",
  "settings.languageSub": "Idioma de la aplicación",
  "settings.saved": "✅ Configuración guardada",
  "settings.demoLoaded": "✅ Datos de demo cargados",
  "settings.cleared": "🗑️ Datos borrados",
  "settings.chooseWeekCost": "Elige una semana y un costo válido",
  "settings.weekUpdated": "✅ Costo de {week} actualizado",

  // Weekly lots breakdown
  "reports.lots": "Lotes",
  // Sigue en el ranking porque las arrobas se recogieron de verdad; la marca
  // es para que un nombre en la lista no se lea como alguien que sigue aquí.
  "reports.inactive": "retirado",

  // Worker detail
  "worker.performance": "Rendimiento",
  "worker.days": "Días activos",
  "worker.byWeek": "Rendimiento por semana",
  "worker.byCrop": "Por cultivo",
  "worker.deletedBadge": "Inactivo",

  // Confirm delete
  "confirm.deleteWorkerTitle": "¿Eliminar recolector?",
  "confirm.deleteWorkerBody":
    "Se ocultará de la lista, pero su historial de recolección se conserva.",
  "confirm.cancel": "Cancelar",
  "confirm.delete": "Eliminar",


  // Weeks and payments
  "week.current": "Esta semana",
  "week.previous": "Semana pasada",
  "week.short": "Sem {n}",
  "week.plots": "Lotes",
  "week.more": "+{n} más",
  "pay.tab": "Pagos",
  "pay.title": "Pagos",
  "pay.toPay": "Por pagar",
  "pay.payAll": "Pagar a todos",
  "pay.pay": "Pagar",
  "pay.payFull": "Pagar todo",
  "pay.payPart": "Pagar una parte",
  "pay.confirm": "Confirmar pago",
  "pay.weOwe": "Le debemos",
  "pay.paid": "Ya pagado",
  "pay.partial": "Abono parcial",
  "pay.credit": "Saldo a favor",
  "pay.remaining": "Falta por pagar",
  "pay.account": "Estado de cuenta",
  "pay.movements": "Movimientos",
  "pay.settle": "Liquidar",
  "pay.settlement": "Liquidación",
  "pay.advance": "Avance",
  "pay.discounts": "Descuentos",
  "pay.amount": "Monto",
  "pay.method": "Forma de pago",
  "pay.cash": "Efectivo",
  "pay.transfer": "Transferencia",
  "pay.note": "Nota (opcional)",
  "pay.half": "Mitad",
  "pay.all": "Todo",
  "pay.leaveCredit": "Deja el resto como saldo a favor",
  "pay.deliverCredit": "Entregar saldo",
  "pay.undo": "Deshacer",
  "pay.empty": "Esta semana no hay nada por pagar.",
  "pay.emptyHistory": "Todavía no le has pagado a nadie. Cuando liquides una semana aparece aquí.",
  "pay.noCredit": "No tiene saldo a favor.",
  "pay.people": "{n} recolectores",
  "pay.success": "Listo. Le pagaste {amount} a {name}.",
  "pay.error": "No se pudo guardar el pago. Vuelve a intentar.",
  "pay.askOne": "¿Pagar {amount} a {name}?",
  "pay.askMany": "¿Pagar {amount} a {n} recolectores?",
  "pay.yes": "Sí, pagar",
  "pay.notNow": "Ahora no",
  "pay.willOwe": "Queda debiendo: {amount}",
  "pay.gross": "Recolección",
  "pay.totalWeek": "Total semana",
  // The part of a settlement this phone holds no weighing for: a jornal or a
  // contract registered on the web (§2.2). Named on the receipt instead of
  // being added silently, because a worker checking the total against the
  // weeks listed has to be able to see why it is bigger.
  "pay.otherWork": "Otros trabajos (en la oficina)",
  "pay.payToday": "A pagar hoy",
  "pay.share": "Compartir comprobante",
  "pay.receipt": "Comprobante de pago",
  "disc.food": "Lata / alimentación",
  "disc.lodging": "Dormida",
  "disc.tools": "Herramienta",
  "disc.store": "Tienda",
  "disc.other": "Otros",
  "pay.paidTo": "Listo. Le pagaste a {n} recolectores.",
  "pay.owed": "Le debemos",
  "pay.settleFirst": "Liquidar y pagar",
  "pay.nothingPending": "No tiene nada pendiente esta semana.",
  "pay.notItemisable": "De este saldo, {amount} son jornales o contratos registrados en la web. Este teléfono solo sabe desglosar las pesadas.",
  "pay.canDeliverHere": "Desde este teléfono se puede entregar {amount}.",
  "pay.provisional": "Provisional: faltan {n} por enviar. Es el saldo que calcula este teléfono.",
  "pay.fromServer": "Saldo completo del servidor, recibido el {when}.",
  "pay.asOf": "al {when}",
  "pay.advanceReceipt": "Comprobante de anticipo",
  "pay.advanceDelivered": "Entregado",
  "pay.advanceReceiptNote": "Esto es un anticipo, no una liquidación. No cierra ninguna semana y no paga ninguna pesada en particular: se descuenta del saldo cuando se liquide.",
  "pay.printAdvance": "Imprimir comprobante",
  "pay.movedToWebTitle": "La liquidación se hace en la web",
  "pay.movedToWebWorker": "Cerrar la semana y pagar contra una liquidación se hacen ahora en la consola de la finca, con señal. Aquí puedes entregar un anticipo e imprimir su comprobante: se descuenta solo cuando se liquide.",
  "pay.movedToWebCrew": "La nómina de la cuadrilla y su planilla se hacen ahora en la consola de la finca. Esta pantalla sigue mostrando a quién se le debe y cuánto, y desde cada persona puedes entregar un anticipo.",
  "pay.asOfProvisional": "al {when} · provisional, faltan {n} por enviar",
  "pay.balanceUnknownShort": "No lo sé",
  "pay.balanceUnknownWhy": "este teléfono aún no ha recibido un saldo",
  "pay.balanceUnknownBody": "El saldo lo lleva el servidor y este teléfono todavía no ha recibido el de esta persona. No es cero: es que no se sabe. Sincroniza para verlo.",
  "pay.balanceTitle": "Saldo a favor",
  "pay.history": "Historial",
  "pay.quick": "Rápido",
  "pay.kind.devengo": "Liquidación",
  "pay.kind.pago": "Pago",
  "pay.kind.anticipo": "Avance",
  "pay.kind.deduccion": "Descuento",
  "pay.kind.ajuste": "Ajuste",
  "pay.kind.reverso": "Reverso",
  "pay.saved": "Guardado.",
  "pay.afterwards": "Queda",
  "pay.newMovement": "Registrar movimiento",
  "pay.owesUs": "Avance pendiente",
  "pay.owesUsBody": "Se descuenta de su próxima liquidación.",
  "pay.saveMovement": "Guardar movimiento",
  "pay.settledNoCash": "Liquidado. El avance cubrió toda la semana, no hay efectivo por entregar.",
  "pay.noCashN": "{n} sin saldo por entregar",
  "pay.failedN": "{n} con error",

  // Performance
  "perf.tab": "Rendimiento",
  "perf.crew": "Cuadrilla",
  "perf.crewSub": "Comparado contra quienes trabajaron el mismo lote el mismo día",
  "perf.crewKgDay": "{unit}/día cuadrilla",
  "perf.realCost": "Costo real por {unit}",
  "perf.budget": "Presupuesto",
  "perf.day": "día",
  "perf.plots": "Lotes",
  "perf.pickers": "{n} recolectores",
  "perf.noArea": "sin área",
  "perf.review": "Pesadas por revisar",
  "perf.anomalies": "{n} pesadas por revisar",
  "perf.empty": "Aún no hay recolecciones para comparar.",
  "perf.rule.impossible": "peso imposible",
  "perf.rule.duplicate": "posible doble registro",
  "perf.rule.digit": "¿un cero de más? normal: {n}",
  "perf.rule.outlier": "muy por encima del lote",
  "perf.rule.future": "fecha futura",
  "perf.noBase": "— sin índice: hacen falta al menos 3 recolectores en el mismo lote el mismo día para comparar.",
  "perf.price": "Precio y rendimiento",
  "perf.priceSub": "Si subir el precio del kilo trajo más cosecha",
  "perf.priceNoGain.one": "La subida de precio no trajo más cosecha. Es margen que se está regalando.",
  "perf.priceNoGain.other": "Las {total} subidas de precio no trajeron más cosecha. Es margen que se está regalando.",
  "perf.priceGain.one": "La subida de precio sí trajo más cosecha.",
  "perf.priceGain.other": "{n} de {total} subidas de precio sí trajeron más cosecha.",
  "perf.priceMoreHands": "La cosecha subió porque entró más gente, no porque cada uno rindiera más.",
  "crop.days": "Días activos",
  "crop.value": "Valor producido",
  "crop.curve": "Curva de cosecha",
  "crop.peak": "Pico en {week}",
  "crop.pickers": "Recolectores en este lote",
  "crop.pickersSub": "Índice comparado solo contra quienes trabajaron aquí",
  "crop.daysHere": "{n} días aquí",
  "crop.weeks": "Por semana",
  "disc.otherLabel": "¿De qué es el descuento?",
  "disc.otherHint": "Ej: transporte, guantes, adelanto de mercado",
  "pay.undone": "Se deshizo el pago.",
  "crop.deleted": "Lote eliminado",
  "confirm.deleteCropTitle": "¿Eliminar este lote?",
  "confirm.deleteCropBody": "Se oculta de la lista, pero se conserva el historial de recolección.",
  "perf.reviewOne": "Revisar pesada",
  "perf.reviewBody": "{weight} de {person} — {reason}. Corrige el peso o descarta la pesada.",
  "perf.newWeight": "Peso correcto ({unit})",
  "perf.correct": "Corregir",
  "perf.discard": "Descartar",
  "perf.keep": "Dejar así",
  "perf.corrected": "Pesada corregida.",
  "perf.discarded": "Pesada descartada.",
  "perf.settled": "No se puede: esta pesada ya está en una liquidación pagada. Anula la liquidación primero.",
  "pay.voidTitle": "¿Anular esta liquidación?",
  "pay.voidBody": "Las pesadas vuelven a quedar pendientes y se podrán corregir. Si ya le pagaste, ese pago pasa a contar como avance y se le descuenta de la próxima liquidación.",
  "pay.void": "Anular",
  "pay.voided": "Liquidación anulada.",
  "pay.voidNote": "Liquidación anulada",
  "peopleAdd.rfidTaken": "Esa placa ya la tiene otro recolector.",
  "worker.perDay": "{unit}/día",
  "perf.badWeight": "Escribe un peso mayor que cero.",
  "crop.windingDown": "La cosecha lleva {n} semanas cayendo fuerte y ya pasó su pico. Considere mover gente a otro lote.",
  "settings.exportTitle": "Exportar datos",
  "settings.exportSub": "Sácalos del teléfono como CSV",
  "settings.exported": "Se exportaron {n} archivos.",
  "settings.exportEmpty": "Todavía no hay datos que exportar.",
  "settings.exportFailed": "No se pudo exportar. Vuelve a intentar.",
  "week.byDay": "Por día",
  "week.dayMeta": "{p} personas · {l} lotes",
  "week.grid": "Quién trabajó dónde",
  "week.gridSub": "Kilos por recolector y lote",
  "week.total": "Total",
  "settings.exportPickups": "Pesadas",
  "settings.exportLedger": "Movimientos",
  "settings.exportBalances": "Saldos",
  "week.byDayAxis": "Por día",
  "week.byPlotAxis": "Por lote",
  "week.gridSubDay": "Kilos por recolector y día",
  "pay.signWorker": "Firma del recolector",
  "pay.signFarm": "Firma de la finca",
  "pay.print": "Imprimir o PDF",
  "pay.payroll": "Planilla de pago",
  "pay.printPayroll": "Imprimir planilla",
  "pay.people.one": "1 recolector",
  "unit.default": "unidad",

  // ---- Sync (docs/sincronizacion.md §7) --------------------------------
  //
  // The wording is the document's, on purpose. "Para liquidar hay que
  // sincronizar" is the sentence §6.1 writes out, and the phrase beside the
  // advance button is the one that tells a pesador what to do instead of
  // leaving them stuck at a disabled button.
  "sync.title": "Sincronización",
  "stack.sync": "Sincronización",
  "stack.syncSetup": "Conectar con la finca",
  "sync.chipOk": "Sincronizado",
  "sync.chipPending": "{n} sin enviar",
  "sync.chipOffline": "Sin señal · {n} pendientes",
  "sync.chipConflicts": "{n} necesitan tu decisión",
  "sync.chipStuck": "No está sincronizando",
  "sync.connectShort": "Conectar",
  "sync.allSent": "Todo enviado",
  "sync.notSentYet": "{n} sin enviar",
  "sync.lastSync": "Última sincronización: {when}",
  "sync.neverSynced": "Este teléfono nunca ha sincronizado",
  "sync.syncNow": "Sincronizar ahora",
  "sync.willRetry": "Se reintenta solo. Nada se pierde mientras tanto.",
  "sync.notRead": "Lo que este usuario no puede leer",
  "sync.needsYou": "{n} necesitan tu decisión",
  "sync.noConflicts": "No hay nada esperando una decisión.",
  "sync.connectTitle": "Conecta este teléfono con tu finca",
  "sync.connectBody": "Entra con el mismo correo y contraseña que usas en la web. Las pesadas que ya están en el teléfono se envían solas.",
  "sync.email": "Correo",
  "sync.password": "Contraseña",
  "sync.connect": "Conectar",
  "sync.passwordNote": "La contraseña no se guarda en el teléfono.",
  "sync.registeredAs": "Conectado como {role}",
  "sync.roleOwner": "dueño",
  "sync.roleAdmin": "administrador",
  "sync.roleWeigher": "pesador",
  "sync.deviceId": "Este teléfono",
  "sync.farmId": "Finca",
  "sync.signOut": "Desconectar",
  "sync.signOutNote": "Desconectar no borra nada: la temporada sigue en el teléfono y lo que falte por enviar se queda esperando.",
  "sync.changesTitle": "Lo que cambia al conectar",
  "sync.changeSettle": "Para liquidar hay que tener señal. Sin señal se entrega un anticipo, que se descuenta solo al liquidar.",
  "sync.changePlots": "Los lotes se crean en la web.",
  "sync.changePrices": "El precio de la semana lo pone el dueño en la web.",
  "sync.errBadCredentials": "Correo o contraseña incorrectos.",
  "sync.errNotVerified": "Falta confirmar el correo desde el mensaje que te llegó.",
  "sync.errSuspended": "Esta finca está suspendida.",
  "sync.errNoSignal": "Sin señal.",
  "sync.errPartial": "Quedaron cambios sin enviar.",
  "sync.errAuth": "Hay que volver a entrar con el correo y la contraseña.",
  "sync.errOtherFarm": "Este teléfono ya está conectado a otra finca.",
  "sync.errOther": "No se pudo conectar ({code}).",
  "sync.errBackoff": "Esperando un momento antes de volver a intentarlo.",
  "sync.errRateLimited": "El servidor pidió esperar un poco. Se reintenta solo.",
  "sync.errServer": "El servidor tuvo un problema. Se reintenta solo.",
  "sync.errAppOld": "Esta versión de la app ya no habla con el servidor. Hay que actualizarla.",
  "sync.errBug": "Algo salió mal y no se arregla reintentando.",
  "sync.errCode": "Código: {code}",
  "sync.wontRetry": "Esto no se arregla solo.",
  "sync.behindTitle": "Faltan cambios por recibir",
  "sync.behindBody": "Se bajó lo que cupo en esta pasada y quedan más en el servidor. Vuelve a sincronizar hasta que este aviso desaparezca; hasta entonces el teléfono no está al día y no se puede liquidar.",
  // §3.4. El servidor guarda 180 días de cambios. Un teléfono que estuvo más
  // tiempo sin señal no se puede poner al día por partes, así que se baja
  // todo otra vez. No es un error y no se pierde nada — pero si no se dice,
  // el contador de «faltan N» salta de once a la temporada entera.
  "sync.bootstrapTitle": "Se está bajando todo de nuevo",
  "sync.bootstrapBody": "Este teléfono pasó demasiado tiempo sin conectarse, así que está volviendo a bajar la temporada completa. No se perdió nada: lo que este teléfono tenía sigue aquí y lo que faltaba por enviar se envía igual. Puede tardar varias pasadas.",
  "sync.behindCount": "El servidor dice que faltan {n}.",
  "sync.chipBehind": "Faltan cambios por recibir",
  "sync.someone": "Alguien",

  // §6.1 — the sentence beside the advance button, word for word.
  "pay.needsSyncTitle": "Para liquidar hay que sincronizar",
  "pay.needsSyncBody": "Sin señal puedes entregar un anticipo: se descuenta solo cuando se liquide.",
  "pay.advanceNow": "Entregar anticipo",
  "pay.advanceAmount": "Anticipo",
  "pay.advanceDone": "Anticipo de {amount} entregado a {name}",
  "pay.syncFirst": "Sincronizar",
  "pay.amountRequired": "Escribe cuánto vas a entregar.",

  // §7.3 — the conflict cards.
  "conflict.alreadySettled": "Cambiaste esta pesada a {qty}, pero ya se pagó en una liquidación. La liquidación no se toca; tu cambio quedó guardado aquí.",
  "conflict.readOnlyTitle": "Un lote o un precio hecho en el teléfono",
  "conflict.readOnlyBody": "Los lotes y el precio de la semana se administran en la web. Esto no se envió y no se perdió: sigue en el teléfono.",
  "conflict.moneyHereTitle": "Dinero que vive en este teléfono",
  "conflict.moneyHereBody": "{n} movimientos por {amount} no se envían sueltos: una liquidación y su pago viajan juntos o el servidor podría pagarlos otra vez.",
  "conflict.moneyHereWhere": "No se pierde nada y no hay nada que decidir. Suben con la importación de temporada, que lleva la liquidación y sus líneas juntas y cuadra cada saldo al centavo antes de escribir.",
  "conflict.moneyHereMore": "y {n} personas más",
  "conflict.settlementHereTitle": "Una liquidación hecha en este teléfono",
  "conflict.settlementHereBody": "Las liquidaciones las emite el servidor (decisión 5). Esta no se envió y no se perdió: sigue en el teléfono con su pago, y sube con la importación de temporada.",
  "conflict.balanceMismatch": "El teléfono calcula {local} y el servidor {server}. Nadie cambió nada: hay que averiguar por qué no cuadran.",
  "conflict.notItemisable": "El saldo completo es {server}. El teléfono solo puede desglosar las pesadas; los jornales y contratos están en la web.",
  // §5.6. Two names and one document. Nobody on this screen may join them:
  // restaurar al que ya existe es un botón de la web, y unir dos fichas aquí
  // sería unir un libro de movimientos que esta pantalla no puede ver.
  "conflict.workerExistsDeleted":
    "Ese documento ya es de {name}, que está retirado en esta finca. No se creó una segunda ficha: hay que reactivar la que ya existe desde la web.",
  // §5.5. Se aprobó una cifra y al llegar al servidor era otra. No se escribió nada.
  "conflict.grossChanged":
    "Se aprobó {expected} y la liquidación ahora suma {actual}. No se guardó nada.",
  "conflict.grossChangedWhy":
    "Entraron {added} pesadas nuevas y salieron {removed}. Vuelve a liquidar con la cifra de ahora.",
  "conflict.grossChangedUnknown":
    "El servidor no puede decir qué cambió porque no se le dijo qué se estaba viendo. Vuelve a liquidar y revisa la cifra antes de confirmar.",
  "conflict.divergedTitle": "El mismo dato, distinto en los dos lados",
  "conflict.diverged": "Este dato ya había llegado al servidor con otro contenido. Nadie pisó nada: tu versión sigue en el teléfono y la del servidor sigue allí. Hay que mirar cuál es la buena.",
  "conflict.rejectedTitle": "El servidor no aceptó un cambio",
  "conflict.understood": "Entendido",
  "conflict.seeHistory": "Ver el historial",
  "conflict.report": "Enviar informe",
  "conflict.closed": "Listo",
  "conflict.reported": "Anotado",

  // ---- §8: la mudanza de la temporada que ya está en el teléfono -------
  //
  // Quien pulsa esto está mudando la nómina de su finca. Las dos frases que
  // no se negocian son «no se subió nada» y «tu teléfono sigue exactamente
  // igual»: son la propiedad en la que descansa todo el plan de §8, y la
  // persona que mira una tarjeta roja no tiene otra forma de saberlo.
  "stack.seasonImport": "Subir la temporada",
  "import.title": "Subir la temporada al servidor",
  "import.intro": "La finca lleva meses en este teléfono y el servidor no la tiene. Esto se la entrega, con las mismas pesadas, las mismas liquidaciones y los mismos saldos.",
  "import.safety": "No borra ni cambia nada de este teléfono. Si algo falla, sigue exactamente igual.",
  "import.notRegistered": "Primero hay que conectar este teléfono con la finca.",
  "import.noMoney": "Solo el dueño o un administrador puede subir la temporada.",
  "import.whatGoes": "Lo que se va a subir",
  "import.range": "Del {from} al {to}",
  "import.workers": "Recolectores",
  "import.plots": "Lotes",
  "import.pickups": "Pesadas",
  "import.settlements": "Liquidaciones",
  "import.lines": "{n} líneas",
  "import.ledger": "Movimientos",
  "import.weekPrices": "Precios de semana",
  "import.kg": "{kg} kg",
  "import.money": "Dinero en juego",
  "import.earned": "Devengado",
  "import.paid": "Pagado",
  "import.balance": "Saldo pendiente",
  "import.balanceNote": "El servidor vuelve a calcular el saldo de las {n} personas. Si uno solo no coincide al centavo, no se guarda nada.",
  "import.upload": "Subir la temporada",
  "import.cannotBuild": "Esta temporada todavía no se puede subir",
  "import.confirmTitle": "¿Subir la temporada?",
  "import.confirmBody": "Se van a subir {n} pesadas y {m} movimientos de dinero.",
  "import.cancel": "Cancelar",
  "import.confirm": "Subir",
  "import.phase.building": "Preparando la temporada…",
  "import.phase.checking": "Comprobando que todo cuadra…",
  "import.phase.beginning": "Hablando con el servidor…",
  "import.phase.sending": "Enviando…",
  "import.phase.committing": "El servidor está comprobando los saldos…",
  "import.phaseSending": "Enviando {rows} filas…",
  "import.dontClose": "Es un solo envío. Si se corta, volver a intentarlo no duplica nada.",
  "import.size": "{mb} MB en un solo envío",
  "import.elapsed": "Llevamos {clock}",
  "import.waitUntil": "Esperamos hasta {min} minutos antes de darlo por perdido.",
  "import.okTitle": "La temporada ya está en el servidor",
  "import.okBalances": "Se comprobaron {n} saldos y todos coinciden al centavo.",
  "import.okCounts": "{workers} recolectores · {records} pesadas · {ledger} movimientos",
  "import.duration": "Tardó {s} segundos.",
  "import.alreadyTitle": "Esta temporada ya estaba subida",
  "import.alreadyBody": "No se subió nada nuevo: la finca ya la tiene.",
  "import.failTitle": "No se subió nada",
  "import.failSafe": "Tu teléfono sigue exactamente igual.",
  "import.rejectedBody": "El servidor calculó saldos distintos, así que lo rechazó entero. Ni media nómina.",
  "import.refusedBody": "Lo que iba a subirse no cuadra con el propio teléfono, así que no salió.",
  "import.brokeBody": "Se cortó a mitad del envío ({code}). Puede que el servidor lo guardara y no llegara la respuesta: volver a intentarlo no duplica nada.",
  "import.problems": "Lo que no cuadra",
  "import.mismatchRow": "{name}: el teléfono dice {phone} y el servidor {server}",
  "import.andMore": "y {n} más",
  "import.retry": "Volver a intentar",
  "import.openTitle": "La temporada de este teléfono no está en el servidor",
  "import.openBody": "Súbela antes de empezar a liquidar desde la web.",
  "import.open": "Subir la temporada",
};

const en: Dict = {
  "nav.home": "Home",
  "nav.workers": "Workers",
  "nav.crops": "Crops",
  "nav.pickup": "Pickup",
  "nav.reports": "Reports",
  "nav.settings": "Settings",
  "nav.back": "Back",
  "stack.newWorker": "New worker",
  "stack.newCrop": "New crop",
  "stack.registerPickup": "Register pickup",

  "home.totalHarvested": "Total harvested",
  "home.pickupsCount": "{n} pickups",
  "home.today": "Today",
  "home.thisWeek": "This week",
  "home.registerPickup": "Register pickup",
  "home.recentActivity": "Recent activity",
  "home.noPickups": "No pickups yet. Tap “Register pickup” to start.",

  "label.workers": "Workers",
  "label.crops": "Crops",
  "label.pickups": "Pickups",

  "people.empty": "No workers yet. Tap + to add one.",
  "people.tag": "tag",

  "peopleAdd.gallery": "Gallery",
  "peopleAdd.camera": "Camera",
  "peopleAdd.removePhoto": "Remove photo",
  "peopleAdd.firstName": "First name *",
  "peopleAdd.lastName": "Last name",
  "peopleAdd.docType": "Document type",
  "peopleAdd.docId": "Document id",
  "peopleAdd.rfid": "RFID tag / card",
  "peopleAdd.rfidHelp": "The tag identifies the worker at the scale.",
  "peopleAdd.save": "Save worker",

  "crops.empty": "No crops yet. Tap + to add one.",

  "cropAdd.type": "Crop type *",
  "cropAdd.measuredIn": "Measured in {unit} · {yield}",
  "cropAdd.lotName": "Plot name *",
  "cropAdd.lotPlaceholder": "e.g. {label} plot 1",
  "cropAdd.variety": "Variety",
  "cropAdd.area": "Planted area (ha)",
  "cropAdd.save": "Save crop",

  "pickup.worker": "Worker",
  "pickup.crop": "Crop",
  "pickup.noWorkers": "No workers yet — add one first.",
  "pickup.noCrops": "No crops yet — add one first.",
  "pickup.weight": "Weight ({unit})",
  "pickup.save": "Save pickup",
  "pickup.saved": "✅ Pickup saved",

  "reports.total": "Total {unit}",
  "reports.pickups": "Pickups",
  "reports.toPay": "To pay",
  "reports.pickers": "Workers",
  "reports.week": "Week",
  "reports.worker": "Worker",
  "reports.crop": "Crop",
  "reports.byWeek": "Harvest by week",
  "reports.byWorker": "Harvest by worker",
  "reports.byCrop": "Harvest by crop",
  "reports.unitsCollected": "{unit} collected",
  "reports.noPickups": "No pickups registered yet.",
  "reports.recent": "Recent pickups",
  "reports.nothing": "Nothing yet.",

  "settings.cropTypeTitle": "Crop type",
  "settings.cropTypeSub": "Pick one to load its default units",
  "settings.unitsTitle": "Units and cost",
  "settings.cropName": "Crop name",
  "settings.unit": "Unit of measure",
  "settings.unitPlaceholder": "kg, bunch, ton…",
  "settings.yieldUnit": "Yield unit",
  "settings.generalCost": "General cost per {unit}",
  "settings.generalCostHelp":
    "This cost applies to every week unless you override it below.",
  "settings.saveConfig": "Save configuration",
  "settings.weekCostsTitle": "Weekly costs",
  "settings.weekCostsSub": "Override the cost per unit for specific weeks",
  "settings.noWeeks": "No pickups registered yet to assign weekly costs.",
  "settings.week": "Week",
  "settings.costPer": "Cost per {unit}",
  "settings.add": "Add",
  "settings.demoTitle": "Demo data",
  "settings.demoSub": "Workers, crops and 4 weeks of pickups",
  "settings.loadDemo": "Load demo",
  "settings.clearAll": "Clear all",
  "settings.wipeTitle": "This erases the season",
  "settings.wipeClearBody":
    "Workers, plots, weighings, settlements and movements for this farm are deleted. There is no backup and this cannot be undone.",
  "settings.wipeSeedBody":
    "Loading the demo erases everything real first: workers, plots, weighings, settlements and movements. There is no backup and this cannot be undone.",
  "settings.wipeConfirm": "Type {name} to confirm",
  "settings.wipeField": "Farm name",
  "settings.wipeCancel": "Cancel",
  "settings.wipeMismatch": "The name does not match",
  "settings.languageTitle": "Language",
  "settings.languageSub": "App language",
  "settings.saved": "✅ Configuration saved",
  "settings.demoLoaded": "✅ Demo data loaded",
  "settings.cleared": "🗑️ Data cleared",
  "settings.chooseWeekCost": "Pick a week and a valid cost",
  "settings.weekUpdated": "✅ Cost for {week} updated",

  "reports.lots": "Lots",
  "reports.inactive": "removed",

  "worker.performance": "Performance",
  "worker.days": "Active days",
  "worker.byWeek": "Performance by week",
  "worker.byCrop": "By crop",
  "worker.deletedBadge": "Inactive",

  "confirm.deleteWorkerTitle": "Delete worker?",
  "confirm.deleteWorkerBody":
    "They'll be hidden from the list, but their harvest history is kept.",
  "confirm.cancel": "Cancel",
  "confirm.delete": "Delete",


  // Weeks and payments
  "week.current": "This week",
  "week.previous": "Last week",
  "week.short": "Wk {n}",
  "week.plots": "Plots",
  "week.more": "+{n} more",
  "pay.tab": "Payments",
  "pay.title": "Payments",
  "pay.toPay": "To pay",
  "pay.payAll": "Pay everyone",
  "pay.pay": "Pay",
  "pay.payFull": "Pay in full",
  "pay.payPart": "Pay part",
  "pay.confirm": "Confirm payment",
  "pay.weOwe": "We owe",
  "pay.paid": "Paid",
  "pay.partial": "Partial payment",
  "pay.credit": "Credit balance",
  "pay.remaining": "Still owed",
  "pay.account": "Account statement",
  "pay.movements": "Movements",
  "pay.settle": "Settle",
  "pay.settlement": "Settlement",
  "pay.advance": "Advance",
  "pay.discounts": "Deductions",
  "pay.amount": "Amount",
  "pay.method": "Payment method",
  "pay.cash": "Cash",
  "pay.transfer": "Transfer",
  "pay.note": "Note (optional)",
  "pay.half": "Half",
  "pay.all": "All",
  "pay.leaveCredit": "Leave the rest as credit",
  "pay.deliverCredit": "Pay out credit",
  "pay.undo": "Undo",
  "pay.empty": "Nothing to pay this week.",
  "pay.emptyHistory": "No payments yet. Settle a week and it shows up here.",
  "pay.noCredit": "No credit balance.",
  "pay.people": "{n} workers",
  "pay.success": "Done. You paid {amount} to {name}.",
  "pay.error": "Could not save the payment. Try again.",
  "pay.askOne": "Pay {amount} to {name}?",
  "pay.askMany": "Pay {amount} to {n} workers?",
  "pay.yes": "Yes, pay",
  "pay.notNow": "Not now",
  "pay.willOwe": "Still owed: {amount}",
  "pay.gross": "Harvest",
  "pay.totalWeek": "Week total",
  "pay.otherWork": "Other work (kept in the office)",
  "pay.payToday": "To pay today",
  "pay.share": "Share receipt",
  "pay.receipt": "Payment receipt",
  "disc.food": "Meals",
  "disc.lodging": "Lodging",
  "disc.tools": "Tools",
  "disc.store": "Store",
  "disc.other": "Other",
  "pay.paidTo": "Done. You paid {n} workers.",
  "pay.owed": "We owe",
  "pay.settleFirst": "Settle and pay",
  "pay.nothingPending": "Nothing pending this week.",
  "pay.notItemisable": "Of this balance, {amount} is day work or contract work booked on the web. This phone can only break down the weighings.",
  "pay.canDeliverHere": "{amount} of it can be handed over from this phone.",
  "pay.provisional": "Provisional: {n} still to send. This is the balance this phone works out.",
  "pay.fromServer": "Full balance from the server, received on {when}.",
  "pay.asOf": "as of {when}",
  "pay.advanceReceipt": "Advance voucher",
  "pay.advanceDelivered": "Handed over",
  "pay.advanceReceiptNote": "This is an advance, not a settlement. It closes no week and pays for no particular weighing: it is deducted from the balance when the settlement is made.",
  "pay.printAdvance": "Print voucher",
  "pay.movedToWebTitle": "Settling is done on the web",
  "pay.movedToWebWorker": "Closing the week and paying against a settlement are now done in the farm console, with signal. Here you can hand over an advance and print its voucher: it is deducted when the settlement is made.",
  "pay.movedToWebCrew": "The crew payroll and its sheet are now done in the farm console. This screen still shows who is owed what, and from each person you can hand over an advance.",
  "pay.asOfProvisional": "as of {when} · provisional, {n} still to send",
  "pay.balanceUnknownShort": "Not known",
  "pay.balanceUnknownWhy": "this phone has not received a balance yet",
  "pay.balanceUnknownBody": "The balance is kept by the server and this phone has not received this person's yet. It is not zero: it is unknown. Sync to see it.",
  "pay.balanceTitle": "Credit balance",
  "pay.history": "History",
  "pay.quick": "Quick",
  "pay.kind.devengo": "Settlement",
  "pay.kind.pago": "Payment",
  "pay.kind.anticipo": "Advance",
  "pay.kind.deduccion": "Deduction",
  "pay.kind.ajuste": "Adjustment",
  "pay.kind.reverso": "Reversal",
  "pay.saved": "Saved.",
  "pay.afterwards": "Left",
  "pay.newMovement": "Add movement",
  "pay.owesUs": "Outstanding advance",
  "pay.owesUsBody": "It comes off their next settlement.",
  "pay.saveMovement": "Save movement",
  "pay.settledNoCash": "Settled. The advance covered the whole week, nothing to hand over.",
  "pay.noCashN": "{n} with nothing to hand over",
  "pay.failedN": "{n} failed",

  // Performance
  "perf.tab": "Performance",
  "perf.crew": "Crew",
  "perf.crewSub": "Compared against whoever worked the same plot the same day",
  "perf.crewKgDay": "crew {unit}/day",
  "perf.realCost": "Real cost per {unit}",
  "perf.budget": "Budget",
  "perf.day": "day",
  "perf.plots": "Plots",
  "perf.pickers": "{n} pickers",
  "perf.noArea": "no area",
  "perf.review": "Pickups to review",
  "perf.anomalies": "{n} pickups to review",
  "perf.empty": "No harvest to compare yet.",
  "perf.rule.impossible": "impossible weight",
  "perf.rule.duplicate": "possible duplicate",
  "perf.rule.digit": "extra zero? usual: {n}",
  "perf.rule.outlier": "far above the plot",
  "perf.rule.future": "future date",
  "perf.noBase": "— no index: at least 3 pickers on the same plot the same day are needed to compare.",
  "perf.price": "Price and output",
  "perf.priceSub": "Whether raising the rate bought more harvest",
  "perf.priceNoGain.one": "The price rise brought no more harvest. That is margin given away.",
  "perf.priceNoGain.other": "All {total} price rises brought no more harvest. That is margin given away.",
  "perf.priceGain.one": "The price rise did bring more harvest.",
  "perf.priceGain.other": "{n} of {total} price rises did bring more harvest.",
  "perf.priceMoreHands": "The harvest grew because more people joined, not because each one produced more.",
  "crop.days": "Active days",
  "crop.value": "Value produced",
  "crop.curve": "Harvest curve",
  "crop.peak": "Peak on {week}",
  "crop.pickers": "Pickers on this plot",
  "crop.pickersSub": "Index compared only against whoever worked here",
  "crop.daysHere": "{n} days here",
  "crop.weeks": "By week",
  "disc.otherLabel": "What is the deduction for?",
  "disc.otherHint": "e.g. transport, gloves, groceries",
  "pay.undone": "Payment undone.",
  "crop.deleted": "Deleted plot",
  "confirm.deleteCropTitle": "Delete this plot?",
  "confirm.deleteCropBody": "It is hidden from the list, but its harvest history is kept.",
  "perf.reviewOne": "Review pickup",
  "perf.reviewBody": "{weight} by {person} — {reason}. Fix the weight or discard the pickup.",
  "perf.newWeight": "Correct weight ({unit})",
  "perf.correct": "Fix",
  "perf.discard": "Discard",
  "perf.keep": "Leave it",
  "perf.corrected": "Pickup corrected.",
  "perf.discarded": "Pickup discarded.",
  "perf.settled": "Not possible: this pickup is already in a paid settlement. Void the settlement first.",
  "pay.voidTitle": "Void this settlement?",
  "pay.voidBody": "Its pickups go back to pending and can be corrected. If you already paid, that payment becomes an advance and comes off their next settlement.",
  "pay.void": "Void",
  "pay.voided": "Settlement voided.",
  "pay.voidNote": "Settlement voided",
  "peopleAdd.rfidTaken": "Another worker already has that tag.",
  "worker.perDay": "{unit}/day",
  "perf.badWeight": "Enter a weight greater than zero.",
  "crop.windingDown": "The harvest has fallen sharply for {n} weeks and is past its peak. Consider moving people to another plot.",
  "settings.exportTitle": "Export data",
  "settings.exportSub": "Get it off the phone as CSV",
  "settings.exported": "{n} files exported.",
  "settings.exportEmpty": "There is no data to export yet.",
  "settings.exportFailed": "Could not export. Try again.",
  "week.byDay": "By day",
  "week.dayMeta": "{p} people · {l} plots",
  "week.grid": "Who worked where",
  "week.gridSub": "Kilos per picker and plot",
  "week.total": "Total",
  "settings.exportPickups": "Pickups",
  "settings.exportLedger": "Movements",
  "settings.exportBalances": "Balances",
  "week.byDayAxis": "By day",
  "week.byPlotAxis": "By plot",
  "week.gridSubDay": "Kilos per picker and day",
  "pay.signWorker": "Worker's signature",
  "pay.signFarm": "Farm's signature",
  "pay.print": "Print or PDF",
  "pay.payroll": "Payroll sheet",
  "pay.printPayroll": "Print payroll",
  "pay.people.one": "1 worker",
  "unit.default": "unit",

  // ---- Sync (docs/sincronizacion.md §7) --------------------------------
  //
  // The wording is the document's, on purpose. "Para liquidar hay que
  // sincronizar" is the sentence §6.1 writes out, and the phrase beside the
  // advance button is the one that tells a pesador what to do instead of
  // leaving them stuck at a disabled button.
  "sync.title": "Sync",
  "stack.sync": "Sync",
  "stack.syncSetup": "Connect to the farm",
  "sync.chipOk": "Synced",
  "sync.chipPending": "{n} not sent",
  "sync.chipOffline": "No signal · {n} pending",
  "sync.chipConflicts": "{n} need your decision",
  "sync.chipStuck": "Not syncing",
  "sync.connectShort": "Connect",
  "sync.allSent": "All sent",
  "sync.notSentYet": "{n} not sent",
  "sync.lastSync": "Last sync: {when}",
  "sync.neverSynced": "This phone has never synced",
  "sync.syncNow": "Sync now",
  "sync.willRetry": "It retries on its own. Nothing is lost meanwhile.",
  "sync.notRead": "What this user cannot read",
  "sync.needsYou": "{n} need your decision",
  "sync.noConflicts": "Nothing is waiting for a decision.",
  "sync.connectTitle": "Connect this phone to your farm",
  "sync.connectBody": "Sign in with the same email and password you use on the web. The weighings already on this phone are sent automatically.",
  "sync.email": "Email",
  "sync.password": "Password",
  "sync.connect": "Connect",
  "sync.passwordNote": "The password is never stored on the phone.",
  "sync.registeredAs": "Connected as {role}",
  "sync.roleOwner": "owner",
  "sync.roleAdmin": "administrator",
  "sync.roleWeigher": "weigher",
  "sync.deviceId": "This phone",
  "sync.farmId": "Farm",
  "sync.signOut": "Disconnect",
  "sync.signOutNote": "Disconnecting deletes nothing: the season stays on the phone and whatever is unsent keeps waiting.",
  "sync.changesTitle": "What changes when you connect",
  "sync.changeSettle": "Settling needs a signal. Without one you can hand over an advance, which is deducted automatically when the settlement is made.",
  "sync.changePlots": "Plots are created on the web.",
  "sync.changePrices": "The weekly price is set by the owner on the web.",
  "sync.errBadCredentials": "Wrong email or password.",
  "sync.errNotVerified": "The email address still has to be confirmed.",
  "sync.errSuspended": "This farm is suspended.",
  "sync.errNoSignal": "No signal.",
  "sync.errPartial": "Some changes were not sent.",
  "sync.errAuth": "You need to sign in again.",
  "sync.errOtherFarm": "This phone is already connected to another farm.",
  "sync.errOther": "Could not connect ({code}).",
  "sync.errBackoff": "Waiting a moment before trying again.",
  "sync.errRateLimited": "The server asked us to wait. It retries on its own.",
  "sync.errServer": "The server had a problem. It retries on its own.",
  "sync.errAppOld": "This version of the app no longer talks to the server. It has to be updated.",
  "sync.errBug": "Something went wrong and retrying will not fix it.",
  "sync.errCode": "Code: {code}",
  "sync.wontRetry": "This one does not fix itself.",
  "sync.behindTitle": "There are still changes to receive",
  "sync.behindBody": "This pass brought down as much as it could and the server still has more. Sync again until this notice goes away; until then the phone is not up to date and cannot settle.",
  "sync.bootstrapTitle": "Downloading everything again",
  "sync.bootstrapBody": "This phone went too long without connecting, so it is downloading the whole season again. Nothing was lost: what this phone had is still here, and anything still to send goes up all the same. It may take several passes.",
  "sync.behindCount": "The server says {n} are still missing.",
  "sync.chipBehind": "Changes still to receive",
  "sync.someone": "Someone",

  // §6.1 — the sentence beside the advance button, word for word.
  "pay.needsSyncTitle": "Settling requires syncing",
  "pay.needsSyncBody": "Without a signal you can hand over an advance: it is deducted automatically when the settlement is made.",
  "pay.advanceNow": "Hand over an advance",
  "pay.advanceAmount": "Advance",
  "pay.advanceDone": "Advance of {amount} handed to {name}",
  "pay.syncFirst": "Sync",
  "pay.amountRequired": "Type how much you are handing over.",

  // §7.3 — the conflict cards.
  "conflict.alreadySettled": "You changed this weighing to {qty}, but it was already paid in a settlement. The settlement is left alone; your change is kept here.",
  "conflict.readOnlyTitle": "A plot or a price made on the phone",
  "conflict.readOnlyBody": "Plots and the weekly price are administered on the web. This was not sent and was not lost: it is still on the phone.",
  "conflict.moneyHereTitle": "Money that lives on this phone",
  "conflict.moneyHereBody": "{n} movements worth {amount} are not sent on their own: a settlement and its payment travel together, or the server could pay them a second time.",
  "conflict.moneyHereWhere": "Nothing is lost and there is nothing to decide. They go up with the season import, which carries the settlement and its lines together and reconciles every balance to the centavo before writing anything.",
  "conflict.moneyHereMore": "and {n} more people",
  "conflict.settlementHereTitle": "A settlement made on this phone",
  "conflict.settlementHereBody": "Settlements are issued by the server (decision 5). This one was not sent and was not lost: it is still on the phone with its payment, and it goes up with the season import.",
  "conflict.balanceMismatch": "The phone works out {local} and the server {server}. Nothing was changed: somebody has to find out why they disagree.",
  "conflict.notItemisable": "The full balance is {server}. The phone can only itemise weighings; day wages and contracts are on the web.",
  "conflict.workerExistsDeleted":
    "That document already belongs to {name}, who is deactivated on this farm. No second file was created: the existing one has to be restored from the web.",
  "conflict.grossChanged":
    "{expected} was approved and the settlement now adds up to {actual}. Nothing was saved.",
  "conflict.grossChangedWhy":
    "{added} weighings came in and {removed} left. Settle again with the figure as it stands now.",
  "conflict.grossChangedUnknown":
    "The server cannot say what changed, because it was not told what was on screen. Settle again and check the figure before confirming.",
  "conflict.divergedTitle": "The same row, different on each side",
  "conflict.diverged": "This row had already reached the server carrying different content. Nothing was overwritten: your version is still on the phone and the server's is still there. Somebody has to decide which is right.",
  "conflict.rejectedTitle": "The server refused a change",
  "conflict.understood": "Understood",
  "conflict.seeHistory": "See the history",
  "conflict.report": "Send a report",
  "conflict.closed": "Done",
  "conflict.reported": "Noted",

  // ---- §8: moving the season that is already on the phone --------------
  "stack.seasonImport": "Upload the season",
  "import.title": "Upload the season to the server",
  "import.intro": "The farm has been on this phone for months and the server does not have it. This hands it over — the same weighings, the same settlements, the same balances.",
  "import.safety": "It deletes and changes nothing on this phone. If anything fails, it stays exactly as it is.",
  "import.notRegistered": "Connect this phone to the farm first.",
  "import.noMoney": "Only the owner or an administrator can upload the season.",
  "import.whatGoes": "What is going up",
  "import.range": "From {from} to {to}",
  "import.workers": "Workers",
  "import.plots": "Plots",
  "import.pickups": "Weighings",
  "import.settlements": "Settlements",
  "import.lines": "{n} lines",
  "import.ledger": "Movements",
  "import.weekPrices": "Weekly prices",
  "import.kg": "{kg} kg",
  "import.money": "Money at stake",
  "import.earned": "Earned",
  "import.paid": "Paid",
  "import.balance": "Outstanding balance",
  "import.balanceNote": "The server works out all {n} balances again. If a single one is off by a centavo, nothing is stored.",
  "import.upload": "Upload the season",
  "import.cannotBuild": "This season cannot be uploaded yet",
  "import.confirmTitle": "Upload the season?",
  "import.confirmBody": "{n} weighings and {m} movements of money are about to go up.",
  "import.cancel": "Cancel",
  "import.confirm": "Upload",
  "import.phase.building": "Packing the season…",
  "import.phase.checking": "Checking that it adds up…",
  "import.phase.beginning": "Talking to the server…",
  "import.phase.sending": "Sending…",
  "import.phase.committing": "The server is checking the balances…",
  "import.phaseSending": "Sending {rows} rows…",
  "import.dontClose": "It is one upload. If it is cut off, starting again duplicates nothing.",
  "import.size": "{mb} MB in a single upload",
  "import.elapsed": "{clock} so far",
  "import.waitUntil": "We wait up to {min} minutes before giving up on it.",
  "import.okTitle": "The season is on the server",
  "import.okBalances": "{n} balances were checked and every one matches to the centavo.",
  "import.okCounts": "{workers} workers · {records} weighings · {ledger} movements",
  "import.duration": "It took {s} seconds.",
  "import.alreadyTitle": "This season was already uploaded",
  "import.alreadyBody": "Nothing new went up: the farm already has it.",
  "import.failTitle": "Nothing was uploaded",
  "import.failSafe": "Your phone is exactly as it was.",
  "import.rejectedBody": "The server worked out different balances, so it refused the whole thing. Not half a payroll.",
  "import.refusedBody": "What was about to go up did not agree with the phone itself, so it did not leave.",
  "import.brokeBody": "It broke off mid-upload ({code}). The server may have stored it and the answer may have been lost: trying again duplicates nothing.",
  "import.problems": "What does not add up",
  "import.mismatchRow": "{name}: the phone says {phone} and the server {server}",
  "import.andMore": "and {n} more",
  "import.retry": "Try again",
  "import.openTitle": "This phone\u2019s season is not on the server",
  "import.openBody": "Upload it before settling from the web.",
  "import.open": "Upload the season",
};

const pt: Dict = {
  "nav.home": "Início",
  "nav.workers": "Colhedores",
  "nav.crops": "Culturas",
  "nav.pickup": "Colheita",
  "nav.reports": "Relatórios",
  "nav.settings": "Ajustes",
  "nav.back": "Voltar",
  "stack.newWorker": "Novo colhedor",
  "stack.newCrop": "Nova cultura",
  "stack.registerPickup": "Registrar colheita",

  "home.totalHarvested": "Total colhido",
  "home.pickupsCount": "{n} colheitas",
  "home.today": "Hoje",
  "home.thisWeek": "Esta semana",
  "home.registerPickup": "Registrar colheita",
  "home.recentActivity": "Atividade recente",
  "home.noPickups": "Ainda não há colheitas. Toque em “Registrar colheita”.",

  "label.workers": "Colhedores",
  "label.crops": "Culturas",
  "label.pickups": "Colheitas",

  "people.empty": "Ainda não há colhedores. Toque em + para adicionar.",
  "people.tag": "cartão",

  "peopleAdd.gallery": "Galeria",
  "peopleAdd.camera": "Câmera",
  "peopleAdd.removePhoto": "Remover foto",
  "peopleAdd.firstName": "Nome *",
  "peopleAdd.lastName": "Sobrenome",
  "peopleAdd.docType": "Tipo de documento",
  "peopleAdd.docId": "Número do documento",
  "peopleAdd.rfid": "Cartão / etiqueta RFID",
  "peopleAdd.rfidHelp": "O cartão identifica o colhedor na balança.",
  "peopleAdd.save": "Salvar colhedor",

  "crops.empty": "Ainda não há culturas. Toque em + para adicionar.",

  "cropAdd.type": "Tipo de cultura *",
  "cropAdd.measuredIn": "Medido em {unit} · {yield}",
  "cropAdd.lotName": "Nome do lote *",
  "cropAdd.lotPlaceholder": "ex. {label} lote 1",
  "cropAdd.variety": "Variedade",
  "cropAdd.area": "Área plantada (ha)",
  "cropAdd.save": "Salvar cultura",

  "pickup.worker": "Colhedor",
  "pickup.crop": "Cultura",
  "pickup.noWorkers": "Nenhum colhedor — adicione um primeiro.",
  "pickup.noCrops": "Nenhuma cultura — adicione uma primeiro.",
  "pickup.weight": "Peso ({unit})",
  "pickup.save": "Salvar colheita",
  "pickup.saved": "✅ Colheita salva",

  "reports.total": "Total {unit}",
  "reports.pickups": "Colheitas",
  "reports.toPay": "A pagar",
  "reports.pickers": "Colhedores",
  "reports.week": "Semana",
  "reports.worker": "Colhedor",
  "reports.crop": "Cultura",
  "reports.byWeek": "Colheita por semana",
  "reports.byWorker": "Colheita por colhedor",
  "reports.byCrop": "Colheita por cultura",
  "reports.unitsCollected": "{unit} colhidos",
  "reports.noPickups": "Ainda não há colheitas registradas.",
  "reports.recent": "Colheitas recentes",
  "reports.nothing": "Nada ainda.",

  "settings.cropTypeTitle": "Tipo de cultura",
  "settings.cropTypeSub": "Escolha um para carregar suas unidades padrão",
  "settings.unitsTitle": "Unidades e custo",
  "settings.cropName": "Nome da cultura",
  "settings.unit": "Unidade de medida",
  "settings.unitPlaceholder": "kg, cacho, tonelada…",
  "settings.yieldUnit": "Unidade de rendimento",
  "settings.generalCost": "Custo geral por {unit}",
  "settings.generalCostHelp":
    "Este custo aplica-se a todas as semanas, salvo se você o substituir abaixo.",
  "settings.saveConfig": "Salvar configuração",
  "settings.weekCostsTitle": "Custos por semana",
  "settings.weekCostsSub": "Substitua o custo por unidade em semanas específicas",
  "settings.noWeeks": "Ainda não há colheitas registradas para atribuir custos por semana.",
  "settings.week": "Semana",
  "settings.costPer": "Custo por {unit}",
  "settings.add": "Adicionar",
  "settings.demoTitle": "Dados de demonstração",
  "settings.demoSub": "Colhedores, culturas e 4 semanas de colheitas",
  "settings.loadDemo": "Carregar demo",
  "settings.clearAll": "Apagar tudo",
  "settings.wipeTitle": "Isto apaga a temporada",
  "settings.wipeClearBody":
    "Colhedores, lotes, pesagens, liquidações e movimentos desta fazenda são apagados. Não há cópia de segurança e não é possível desfazer.",
  "settings.wipeSeedBody":
    "Carregar a demo apaga primeiro tudo o que é real: colhedores, lotes, pesagens, liquidações e movimentos. Não há cópia de segurança e não é possível desfazer.",
  "settings.wipeConfirm": "Escreva {name} para confirmar",
  "settings.wipeField": "Nome da fazenda",
  "settings.wipeCancel": "Cancelar",
  "settings.wipeMismatch": "O nome não coincide",
  "settings.languageTitle": "Idioma",
  "settings.languageSub": "Idioma do aplicativo",
  "settings.saved": "✅ Configuração salva",
  "settings.demoLoaded": "✅ Dados de demo carregados",
  "settings.cleared": "🗑️ Dados apagados",
  "settings.chooseWeekCost": "Escolha uma semana e um custo válido",
  "settings.weekUpdated": "✅ Custo de {week} atualizado",

  "reports.lots": "Lotes",
  "reports.inactive": "retirado",

  "worker.performance": "Desempenho",
  "worker.days": "Dias ativos",
  "worker.byWeek": "Desempenho por semana",
  "worker.byCrop": "Por cultura",
  "worker.deletedBadge": "Inativo",

  "confirm.deleteWorkerTitle": "Excluir colhedor?",
  "confirm.deleteWorkerBody":
    "Ele será ocultado da lista, mas o histórico de colheita é mantido.",
  "confirm.cancel": "Cancelar",
  "confirm.delete": "Excluir",


  // Weeks and payments
  "week.current": "Esta semana",
  "week.previous": "Semana passada",
  "week.short": "Sem. {n}",
  "week.plots": "Lotes",
  "week.more": "+{n} mais",
  "pay.tab": "Pagamentos",
  "pay.title": "Pagamentos",
  "pay.toPay": "A pagar",
  "pay.payAll": "Pagar a todos",
  "pay.pay": "Pagar",
  "pay.payFull": "Pagar tudo",
  "pay.payPart": "Pagar uma parte",
  "pay.confirm": "Confirmar pagamento",
  "pay.weOwe": "Devemos",
  "pay.paid": "Já pago",
  "pay.partial": "Pagamento parcial",
  "pay.credit": "Saldo a favor",
  "pay.remaining": "Falta pagar",
  "pay.account": "Extrato da conta",
  "pay.movements": "Movimentos",
  "pay.settle": "Liquidar",
  "pay.settlement": "Liquidação",
  "pay.advance": "Adiantamento",
  "pay.discounts": "Descontos",
  "pay.amount": "Valor",
  "pay.method": "Forma de pagamento",
  "pay.cash": "Dinheiro",
  "pay.transfer": "Transferência",
  "pay.note": "Nota (opcional)",
  "pay.half": "Metade",
  "pay.all": "Tudo",
  "pay.leaveCredit": "Deixar o resto como saldo a favor",
  "pay.deliverCredit": "Entregar saldo",
  "pay.undo": "Desfazer",
  "pay.empty": "Nada a pagar nesta semana.",
  "pay.emptyHistory": "Ainda não pagou ninguém. Ao liquidar uma semana aparece aqui.",
  "pay.noCredit": "Não tem saldo a favor.",
  "pay.people": "{n} colhedores",
  "pay.success": "Pronto. Você pagou {amount} a {name}.",
  "pay.error": "Não foi possível salvar o pagamento. Tente de novo.",
  "pay.askOne": "Pagar {amount} a {name}?",
  "pay.askMany": "Pagar {amount} a {n} colhedores?",
  "pay.yes": "Sim, pagar",
  "pay.notNow": "Agora não",
  "pay.willOwe": "Fica devendo: {amount}",
  "pay.gross": "Colheita",
  "pay.totalWeek": "Total da semana",
  "pay.otherWork": "Outros trabalhos (no escritório)",
  "pay.payToday": "A pagar hoje",
  "pay.share": "Compartilhar comprovante",
  "pay.receipt": "Comprovante de pagamento",
  "disc.food": "Alimentação",
  "disc.lodging": "Dormida",
  "disc.tools": "Ferramenta",
  "disc.store": "Loja",
  "disc.other": "Outros",
  "pay.paidTo": "Pronto. Você pagou a {n} colhedores.",
  "pay.owed": "Devemos",
  "pay.settleFirst": "Liquidar e pagar",
  "pay.nothingPending": "Nada pendente nesta semana.",
  "pay.notItemisable": "Deste saldo, {amount} são diárias ou contratos registrados na web. Este telefone só sabe detalhar as pesagens.",
  "pay.canDeliverHere": "Deste telefone dá para entregar {amount}.",
  "pay.provisional": "Provisório: faltam {n} para enviar. É o saldo que este telefone calcula.",
  "pay.fromServer": "Saldo completo do servidor, recebido em {when}.",
  "pay.asOf": "em {when}",
  "pay.advanceReceipt": "Comprovante de adiantamento",
  "pay.advanceDelivered": "Entregue",
  "pay.advanceReceiptNote": "Isto é um adiantamento, não um acerto. Não fecha nenhuma semana e não paga nenhuma pesagem em particular: é descontado do saldo quando o acerto for feito.",
  "pay.printAdvance": "Imprimir comprovante",
  "pay.movedToWebTitle": "O acerto faz-se na web",
  "pay.movedToWebWorker": "Fechar a semana e pagar contra um acerto fazem-se agora na consola da fazenda, com sinal. Aqui podes entregar um adiantamento e imprimir o seu comprovante: é descontado quando o acerto for feito.",
  "pay.movedToWebCrew": "A folha de pagamento da equipa e a sua planilha fazem-se agora na consola da fazenda. Este ecrã continua a mostrar a quem se deve e quanto, e a partir de cada pessoa podes entregar um adiantamento.",
  "pay.asOfProvisional": "em {when} · provisório, faltam {n} para enviar",
  "pay.balanceUnknownShort": "Não sei",
  "pay.balanceUnknownWhy": "este telefone ainda não recebeu um saldo",
  "pay.balanceUnknownBody": "O saldo é do servidor e este telefone ainda não recebeu o desta pessoa. Não é zero: é desconhecido. Sincroniza para o ver.",
  "pay.balanceTitle": "Saldo a favor",
  "pay.history": "Histórico",
  "pay.quick": "Rápido",
  "pay.kind.devengo": "Liquidação",
  "pay.kind.pago": "Pagamento",
  "pay.kind.anticipo": "Adiantamento",
  "pay.kind.deduccion": "Desconto",
  "pay.kind.ajuste": "Ajuste",
  "pay.kind.reverso": "Estorno",
  "pay.saved": "Salvo.",
  "pay.afterwards": "Fica",
  "pay.newMovement": "Registrar movimento",
  "pay.owesUs": "Adiantamento pendente",
  "pay.owesUsBody": "Será descontado na próxima liquidação.",
  "pay.saveMovement": "Salvar movimento",
  "pay.settledNoCash": "Liquidado. O adiantamento cobriu a semana toda, nada a entregar.",
  "pay.noCashN": "{n} sem saldo a entregar",
  "pay.failedN": "{n} com erro",

  // Performance
  "perf.tab": "Desempenho",
  "perf.crew": "Equipe",
  "perf.crewSub": "Comparado com quem trabalhou no mesmo lote no mesmo dia",
  "perf.crewKgDay": "{unit}/dia equipe",
  "perf.realCost": "Custo real por {unit}",
  "perf.budget": "Orçamento",
  "perf.day": "dia",
  "perf.plots": "Lotes",
  "perf.pickers": "{n} colhedores",
  "perf.noArea": "sem área",
  "perf.review": "Pesagens a revisar",
  "perf.anomalies": "{n} pesagens a revisar",
  "perf.empty": "Ainda não há colheita para comparar.",
  "perf.rule.impossible": "peso impossível",
  "perf.rule.duplicate": "possível duplicata",
  "perf.rule.digit": "zero a mais? normal: {n}",
  "perf.rule.outlier": "muito acima do lote",
  "perf.rule.future": "data futura",
  "perf.noBase": "— sem índice: são necessários ao menos 3 colhedores no mesmo lote no mesmo dia.",
  "perf.price": "Preço e desempenho",
  "perf.priceSub": "Se subir o preço do quilo trouxe mais colheita",
  "perf.priceNoGain.one": "O aumento de preço não trouxe mais colheita. É margem sendo dada.",
  "perf.priceNoGain.other": "Os {total} aumentos de preço não trouxeram mais colheita. É margem sendo dada.",
  "perf.priceGain.one": "O aumento de preço trouxe mais colheita.",
  "perf.priceGain.other": "{n} de {total} aumentos de preço trouxeram mais colheita.",
  "perf.priceMoreHands": "A colheita subiu porque entrou mais gente, não porque cada um rendeu mais.",
  "crop.days": "Dias ativos",
  "crop.value": "Valor produzido",
  "crop.curve": "Curva da colheita",
  "crop.peak": "Pico em {week}",
  "crop.pickers": "Colhedores neste lote",
  "crop.pickersSub": "Índice comparado só com quem trabalhou aqui",
  "crop.daysHere": "{n} dias aqui",
  "crop.weeks": "Por semana",
  "disc.otherLabel": "Do que é o desconto?",
  "disc.otherHint": "Ex: transporte, luvas, mercado",
  "pay.undone": "Pagamento desfeito.",
  "crop.deleted": "Lote excluído",
  "confirm.deleteCropTitle": "Excluir este lote?",
  "confirm.deleteCropBody": "É ocultado da lista, mas o histórico de colheita é mantido.",
  "perf.reviewOne": "Revisar pesagem",
  "perf.reviewBody": "{weight} de {person} — {reason}. Corrija o peso ou descarte a pesagem.",
  "perf.newWeight": "Peso correto ({unit})",
  "perf.correct": "Corrigir",
  "perf.discard": "Descartar",
  "perf.keep": "Deixar assim",
  "perf.corrected": "Pesagem corrigida.",
  "perf.discarded": "Pesagem descartada.",
  "perf.settled": "Não é possível: esta pesagem já está numa liquidação paga. Anule a liquidação primeiro.",
  "pay.voidTitle": "Anular esta liquidação?",
  "pay.voidBody": "As pesagens voltam a ficar pendentes e poderão ser corrigidas. Se já pagou, esse pagamento passa a contar como adiantamento e será descontado na próxima liquidação.",
  "pay.void": "Anular",
  "pay.voided": "Liquidação anulada.",
  "pay.voidNote": "Liquidação anulada",
  "peopleAdd.rfidTaken": "Outro colhedor já tem essa placa.",
  "worker.perDay": "{unit}/dia",
  "perf.badWeight": "Digite um peso maior que zero.",
  "crop.windingDown": "A colheita caiu forte por {n} semanas e já passou do pico. Considere mover gente para outro lote.",
  "settings.exportTitle": "Exportar dados",
  "settings.exportSub": "Tire-os do telefone como CSV",
  "settings.exported": "{n} arquivos exportados.",
  "settings.exportEmpty": "Ainda não há dados para exportar.",
  "settings.exportFailed": "Não foi possível exportar. Tente de novo.",
  "week.byDay": "Por dia",
  "week.dayMeta": "{p} pessoas · {l} lotes",
  "week.grid": "Quem trabalhou onde",
  "week.gridSub": "Quilos por colhedor e lote",
  "week.total": "Total",
  "settings.exportPickups": "Pesagens",
  "settings.exportLedger": "Movimentos",
  "settings.exportBalances": "Saldos",
  "week.byDayAxis": "Por dia",
  "week.byPlotAxis": "Por lote",
  "week.gridSubDay": "Quilos por colhedor e dia",
  "pay.signWorker": "Assinatura do colhedor",
  "pay.signFarm": "Assinatura da fazenda",
  "pay.print": "Imprimir ou PDF",
  "pay.payroll": "Folha de pagamento",
  "pay.printPayroll": "Imprimir folha",
  "pay.people.one": "1 colhedor",
  "unit.default": "unidade",

  // ---- Sync (docs/sincronizacion.md §7) --------------------------------
  //
  // The wording is the document's, on purpose. "Para liquidar hay que
  // sincronizar" is the sentence §6.1 writes out, and the phrase beside the
  // advance button is the one that tells a pesador what to do instead of
  // leaving them stuck at a disabled button.
  "sync.title": "Sincronização",
  "stack.sync": "Sincronização",
  "stack.syncSetup": "Conectar à fazenda",
  "sync.chipOk": "Sincronizado",
  "sync.chipPending": "{n} por enviar",
  "sync.chipOffline": "Sem sinal · {n} pendentes",
  "sync.chipConflicts": "{n} precisam da sua decisão",
  "sync.chipStuck": "Não está sincronizando",
  "sync.connectShort": "Conectar",
  "sync.allSent": "Tudo enviado",
  "sync.notSentYet": "{n} por enviar",
  "sync.lastSync": "Última sincronização: {when}",
  "sync.neverSynced": "Este telefone nunca sincronizou",
  "sync.syncNow": "Sincronizar agora",
  "sync.willRetry": "Tenta de novo sozinho. Nada se perde nesse meio-tempo.",
  "sync.notRead": "O que este usuário não pode ler",
  "sync.needsYou": "{n} precisam da sua decisão",
  "sync.noConflicts": "Não há nada esperando uma decisão.",
  "sync.connectTitle": "Conecte este telefone à sua fazenda",
  "sync.connectBody": "Entre com o mesmo e-mail e senha que usa na web. As pesagens que já estão no telefone são enviadas sozinhas.",
  "sync.email": "E-mail",
  "sync.password": "Senha",
  "sync.connect": "Conectar",
  "sync.passwordNote": "A senha não fica guardada no telefone.",
  "sync.registeredAs": "Conectado como {role}",
  "sync.roleOwner": "dono",
  "sync.roleAdmin": "administrador",
  "sync.roleWeigher": "pesador",
  "sync.deviceId": "Este telefone",
  "sync.farmId": "Fazenda",
  "sync.signOut": "Desconectar",
  "sync.signOutNote": "Desconectar não apaga nada: a safra continua no telefone e o que falta enviar fica esperando.",
  "sync.changesTitle": "O que muda ao conectar",
  "sync.changeSettle": "Para acertar é preciso ter sinal. Sem sinal, entrega-se um adiantamento, que é descontado sozinho no acerto.",
  "sync.changePlots": "Os lotes são criados na web.",
  "sync.changePrices": "O preço da semana é definido pelo dono na web.",
  "sync.errBadCredentials": "E-mail ou senha incorretos.",
  "sync.errNotVerified": "Falta confirmar o e-mail pela mensagem que chegou.",
  "sync.errSuspended": "Esta fazenda está suspensa.",
  "sync.errNoSignal": "Sem sinal.",
  "sync.errPartial": "Ficaram mudanças por enviar.",
  "sync.errAuth": "É preciso entrar de novo com e-mail e senha.",
  "sync.errOtherFarm": "Este telefone já está conectado a outra fazenda.",
  "sync.errOther": "Não foi possível conectar ({code}).",
  "sync.errBackoff": "Esperando um momento antes de tentar de novo.",
  "sync.errRateLimited": "O servidor pediu para esperar um pouco. Tenta de novo sozinho.",
  "sync.errServer": "O servidor teve um problema. Tenta de novo sozinho.",
  "sync.errAppOld": "Esta versão do app já não fala com o servidor. Precisa ser atualizada.",
  "sync.errBug": "Algo deu errado e tentar de novo não resolve.",
  "sync.errCode": "Código: {code}",
  "sync.wontRetry": "Isto não se resolve sozinho.",
  "sync.behindTitle": "Faltam mudanças para receber",
  "sync.behindBody": "Baixou o que coube nesta passada e ainda há mais no servidor. Sincronize de novo até este aviso sumir; até lá o telefone não está em dia e não dá para liquidar.",
  "sync.bootstrapTitle": "Baixando tudo de novo",
  "sync.bootstrapBody": "Este telefone passou tempo demais sem conectar, então está baixando a temporada inteira de novo. Nada foi perdido: o que este telefone tinha continua aqui, e o que faltava enviar é enviado do mesmo jeito. Pode levar várias passadas.",
  "sync.behindCount": "O servidor diz que faltam {n}.",
  "sync.chipBehind": "Faltam mudanças para receber",
  "sync.someone": "Alguém",

  // §6.1 — the sentence beside the advance button, word for word.
  "pay.needsSyncTitle": "Para acertar é preciso sincronizar",
  "pay.needsSyncBody": "Sem sinal você pode entregar um adiantamento: ele é descontado sozinho no acerto.",
  "pay.advanceNow": "Entregar adiantamento",
  "pay.advanceAmount": "Adiantamento",
  "pay.advanceDone": "Adiantamento de {amount} entregue a {name}",
  "pay.syncFirst": "Sincronizar",
  "pay.amountRequired": "Escreve quanto vais entregar.",

  // §7.3 — the conflict cards.
  "conflict.alreadySettled": "Você mudou esta pesagem para {qty}, mas ela já foi paga num acerto. O acerto não é mexido; sua mudança ficou guardada aqui.",
  "conflict.readOnlyTitle": "Um lote ou um preço feito no telefone",
  "conflict.readOnlyBody": "Os lotes e o preço da semana são administrados na web. Isto não foi enviado e não se perdeu: continua no telefone.",
  "conflict.moneyHereTitle": "Dinheiro que vive neste telefone",
  "conflict.moneyHereBody": "{n} movimentos por {amount} não são enviados soltos: um acerto e o seu pagamento viajam juntos, ou o servidor poderia pagá-los outra vez.",
  "conflict.moneyHereWhere": "Nada se perde e não há nada a decidir. Sobem com a importação da temporada, que leva o acerto e as suas linhas juntas e confere cada saldo ao centavo antes de escrever.",
  "conflict.moneyHereMore": "e mais {n} pessoas",
  "conflict.settlementHereTitle": "Um acerto feito neste telefone",
  "conflict.settlementHereBody": "Os acertos são emitidos pelo servidor (decisão 5). Este não foi enviado e não se perdeu: continua no telefone com o seu pagamento, e sobe com a importação da temporada.",
  "conflict.balanceMismatch": "O telefone calcula {local} e o servidor {server}. Ninguém mudou nada: é preciso descobrir por que não batem.",
  "conflict.notItemisable": "O saldo completo é {server}. O telefone só consegue detalhar as pesagens; as diárias e contratos estão na web.",
  "conflict.workerExistsDeleted":
    "Esse documento já é de {name}, que está desativado nesta fazenda. Não foi criada uma segunda ficha: é preciso reativar a que já existe pela web.",
  "conflict.grossChanged":
    "Foi aprovado {expected} e o acerto agora soma {actual}. Nada foi salvo.",
  "conflict.grossChangedWhy":
    "Entraram {added} pesagens novas e saíram {removed}. Faça o acerto de novo com o valor atual.",
  "conflict.grossChangedUnknown":
    "O servidor não consegue dizer o que mudou, porque não lhe disseram o que estava na tela. Faça o acerto de novo e confira o valor antes de confirmar.",
  "conflict.divergedTitle": "O mesmo dado, diferente dos dois lados",
  "conflict.diverged": "Este dado já tinha chegado ao servidor com outro conteúdo. Nada foi sobrescrito: a sua versão continua no telefone e a do servidor continua lá. Alguém tem que ver qual é a boa.",
  "conflict.rejectedTitle": "O servidor não aceitou uma mudança",
  "conflict.understood": "Entendido",
  "conflict.seeHistory": "Ver o histórico",
  "conflict.report": "Enviar relatório",
  "conflict.closed": "Pronto",
  "conflict.reported": "Anotado",

  // ---- §8: a mudança da safra que já está no telefone ------------------
  "stack.seasonImport": "Subir a safra",
  "import.title": "Subir a safra para o servidor",
  "import.intro": "A fazenda está há meses neste telefone e o servidor não a tem. Isto a entrega, com as mesmas pesagens, os mesmos acertos e os mesmos saldos.",
  "import.safety": "Não apaga nem muda nada deste telefone. Se algo falhar, ele continua exatamente igual.",
  "import.notRegistered": "Primeiro é preciso conectar este telefone à fazenda.",
  "import.noMoney": "Só o dono ou um administrador pode subir a safra.",
  "import.whatGoes": "O que vai subir",
  "import.range": "De {from} a {to}",
  "import.workers": "Colhedores",
  "import.plots": "Lotes",
  "import.pickups": "Pesagens",
  "import.settlements": "Acertos",
  "import.lines": "{n} linhas",
  "import.ledger": "Movimentos",
  "import.weekPrices": "Preços da semana",
  "import.kg": "{kg} kg",
  "import.money": "Dinheiro em jogo",
  "import.earned": "Ganho",
  "import.paid": "Pago",
  "import.balance": "Saldo pendente",
  "import.balanceNote": "O servidor recalcula o saldo das {n} pessoas. Se um só não bater ao centavo, nada é guardado.",
  "import.upload": "Subir a safra",
  "import.cannotBuild": "Esta safra ainda não pode subir",
  "import.confirmTitle": "Subir a safra?",
  "import.confirmBody": "Vão subir {n} pesagens e {m} movimentos de dinheiro.",
  "import.cancel": "Cancelar",
  "import.confirm": "Subir",
  "import.phase.building": "Preparando a safra…",
  "import.phase.checking": "Conferindo se tudo bate…",
  "import.phase.beginning": "Falando com o servidor…",
  "import.phase.sending": "Enviando…",
  "import.phase.committing": "O servidor está conferindo os saldos…",
  "import.phaseSending": "Enviando {rows} linhas…",
  "import.dontClose": "É um envio só. Se cair, tentar de novo não duplica nada.",
  "import.size": "{mb} MB num único envio",
  "import.elapsed": "Já vão {clock}",
  "import.waitUntil": "Esperamos até {min} minutos antes de desistir.",
  "import.okTitle": "A safra já está no servidor",
  "import.okBalances": "Foram conferidos {n} saldos e todos batem ao centavo.",
  "import.okCounts": "{workers} colhedores · {records} pesagens · {ledger} movimentos",
  "import.duration": "Levou {s} segundos.",
  "import.alreadyTitle": "Esta safra já tinha subido",
  "import.alreadyBody": "Nada de novo subiu: a fazenda já a tem.",
  "import.failTitle": "Nada subiu",
  "import.failSafe": "Seu telefone continua exatamente igual.",
  "import.rejectedBody": "O servidor calculou saldos diferentes e recusou tudo. Nem meia folha.",
  "import.refusedBody": "O que ia subir não bate com o próprio telefone, então não saiu.",
  "import.brokeBody": "Caiu no meio do envio ({code}). Pode ser que o servidor tenha guardado e a resposta se perdeu: tentar de novo não duplica nada.",
  "import.problems": "O que não bate",
  "import.mismatchRow": "{name}: o telefone diz {phone} e o servidor {server}",
  "import.andMore": "e mais {n}",
  "import.retry": "Tentar de novo",
  "import.openTitle": "A safra deste telefone não está no servidor",
  "import.openBody": "Suba antes de começar a acertar pela web.",
  "import.open": "Subir a safra",
};

const DICTS: Record<Lang, Dict> = { es, en, pt };

export function translate(lang: Lang, key: string, vars?: Record<string, string | number>) {
  let s = DICTS[lang][key] ?? DICTS.es[key] ?? key;
  if (vars) {
    for (const k of Object.keys(vars)) s = s.replace(new RegExp(`\\{${k}\\}`, "g"), String(vars[k]));
  }
  return s;
}

/** "Esta semana" / "Semana pasada", or null for any other week. */
export function weekTag(mondayISO: string, lang: Lang, now = new Date()): string | null {
  const thisMonday = mondayOf(now);
  if (mondayISO === thisMonday) return translate(lang, "week.current");
  const lastMonday = addDays(parseDay(thisMonday), -7).toISOString().slice(0, 10);
  if (mondayISO === lastMonday) return translate(lang, "week.previous");
  return null;
}


