// Command dbdiagram writes docs/database.md: a Mermaid ER diagram of the
// schema that the migrations in services/api/migrations produce, read back
// from a real Postgres instead of written by hand.
//
// It is generated so that it cannot drift. CI applies every migration to a
// scratch database, runs this, and fails when the committed file differs, so
// a pull request that adds a migration carries the regenerated diagram too.
//
//	make db-diagram                      # from services/api: throwaway Postgres in docker
//	go run ./cmd/dbdiagram -migrate -out ../../docs/database.md   # against ADMIN_DATABASE_URL
//
// Only the schema is read. Nothing in the output depends on data, on the time
// of day or on the Postgres host, so two runs over the same migrations are
// byte-for-byte equal.
package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"io/fs"
	"log"
	"os"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/ojardila/bascula/services/api/internal/store"
	"github.com/ojardila/bascula/services/api/migrations"
)

// Schemas the migrations own. public holds the farm data; registry the
// cross-farm identity registry (00007). PostGIS's spatial_ref_sys and goose's
// bookkeeping table are infrastructure, not our model.
var schemas = []string{"public", "registry"}

var skipTables = map[string]bool{
	"public.goose_db_version": true,
	"public.spatial_ref_sys":  true,
}

type column struct {
	name     string
	typ      string
	notNull  bool
	pk       bool
	fk       bool
	unique   bool
	position int
}

type table struct {
	schema, name string
	kind         string // r, p (tables) or v, m (views)
	comment      string
	columns      []*column
}

func (t *table) qualified() string { return t.schema + "." + t.name }

// id is the Mermaid entity name. Tables outside public keep their schema so
// registry.persons can never be mistaken for a public table of the same name.
func (t *table) id() string {
	if t.schema == "public" {
		return t.name
	}
	return t.schema + "_" + t.name
}

type foreignKey struct {
	name          string
	child, parent string // qualified names
	childCols     []string
	parentCols    []string
	nullable      bool
	oneToOne      bool
}

func main() {
	out := flag.String("out", "", "file to write (default: stdout)")
	doMigrate := flag.Bool("migrate", false, "apply every migration to ADMIN_DATABASE_URL first (use a scratch database)")
	flag.Parse()

	dsn := os.Getenv("ADMIN_DATABASE_URL")
	if dsn == "" {
		log.Fatal("ADMIN_DATABASE_URL is not set")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	if *doMigrate {
		if err := store.MigrateDev(ctx, dsn); err != nil {
			log.Fatalf("migrate: %v", err)
		}
	}

	conn, err := pgx.Connect(ctx, dsn)
	if err != nil {
		log.Fatalf("connect: %v", err)
	}
	defer conn.Close(ctx)

	doc, err := render(ctx, conn)
	if err != nil {
		log.Fatal(err)
	}
	if *out == "" {
		os.Stdout.Write(doc)
		return
	}
	if err := os.WriteFile(*out, doc, 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("wrote %s", *out)
}

func render(ctx context.Context, conn *pgx.Conn) ([]byte, error) {
	latest, err := latestMigration(ctx, conn)
	if err != nil {
		return nil, err
	}
	tables, err := loadTables(ctx, conn)
	if err != nil {
		return nil, err
	}
	fks, err := loadForeignKeys(ctx, conn, tables)
	if err != nil {
		return nil, err
	}

	var b bytes.Buffer
	w := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }

	w("<!-- GENERATED FILE. DO NOT EDIT BY HAND.\n")
	w("     Regenerate with `make db-diagram` (from services/api or the repo root).\n")
	w("     CI fails when this file does not match the migrations. -->\n\n")
	w("# Database diagram\n\n")
	w("Schema after applying every migration up to and including **%s**.\n\n", latest)
	w("Generated by `services/api/cmd/dbdiagram` from a scratch Postgres with all of\n")
	w("`services/api/migrations` applied, so it shows what the database really is,\n")
	w("not what someone remembered to draw. Any pull request that adds a migration\n")
	w("must include this file regenerated (`make db-diagram`); the `api` CI job\n")
	w("checks it. The narrative design lives in [modelo-datos.md](modelo-datos.md).\n\n")
	w("Legend: `PK` primary key, `FK` foreign key, `UK` unique. A quoted note after a\n")
	w("column gives the exact Postgres type when the diagram had to shorten it, and\n")
	w("`null` when the column accepts NULL. Relations point from the referenced table\n")
	w("to the table holding the foreign key; the label is the foreign-key column\n")
	w("(references inside a farm are composite with `farm_id`, which the label omits).\n\n")

	w("```mermaid\nerDiagram\n")
	for _, t := range tables {
		if !isTable(t) {
			continue
		}
		if t.schema == "public" {
			w("    %s {\n", t.id())
		} else {
			w("    %s[\"%s\"] {\n", t.id(), t.qualified())
		}
		for _, c := range t.columns {
			short, exact := mermaidType(c.typ)
			var keys []string
			if c.pk {
				keys = append(keys, "PK")
			}
			if c.fk {
				keys = append(keys, "FK")
			}
			if c.unique && !c.pk {
				keys = append(keys, "UK")
			}
			var notes []string
			if exact {
				notes = append(notes, c.typ)
			}
			if !c.notNull {
				notes = append(notes, "null")
			}
			line := fmt.Sprintf("        %s %s", short, c.name)
			if len(keys) > 0 {
				line += " " + strings.Join(keys, ", ")
			}
			if len(notes) > 0 {
				line += fmt.Sprintf(" \"%s\"", strings.Join(notes, ", "))
			}
			w("%s\n", line)
		}
		w("    }\n")
	}
	byName := map[string]*table{}
	for _, t := range tables {
		byName[t.qualified()] = t
	}
	for _, fk := range fks {
		parent, child := byName[fk.parent], byName[fk.child]
		left := "||"
		if fk.nullable {
			left = "|o"
		}
		right := "o{"
		if fk.oneToOne {
			right = "o|"
		}
		w("    %s %s--%s %s : \"%s\"\n", parent.id(), left, right, child.id(), fkLabel(fk.childCols))
	}
	w("```\n\n")

	w("## Tables\n\n")
	w("| Table | Columns | Description |\n|---|---|---|\n")
	for _, t := range tables {
		if !isTable(t) {
			continue
		}
		w("| `%s` | %d | %s |\n", t.qualified(), len(t.columns), mdCell(t.comment))
	}
	var views []*table
	for _, t := range tables {
		if !isTable(t) {
			views = append(views, t)
		}
	}
	if len(views) > 0 {
		w("\n## Views\n\n")
		w("| View | Columns | Description |\n|---|---|---|\n")
		for _, v := range views {
			names := make([]string, len(v.columns))
			for i, c := range v.columns {
				names[i] = c.name
			}
			w("| `%s` | %s | %s |\n", v.qualified(), mdCell(strings.Join(names, ", ")), mdCell(v.comment))
		}
	}
	return b.Bytes(), nil
}

// fkLabel names the foreign-key columns. Most references inside a farm are
// composite (farm_id, x_id) so a row can never point into another farm; the
// farm_id half is the same on every such line and only hides the column that
// says what the relation is, so it is left out when there is something else.
func fkLabel(cols []string) string {
	var rest []string
	for _, c := range cols {
		if c != "farm_id" {
			rest = append(rest, c)
		}
	}
	if len(rest) == 0 {
		rest = cols
	}
	return strings.Join(rest, ", ")
}

func isTable(t *table) bool { return t.kind == "r" || t.kind == "p" }

func mdCell(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	s = strings.ReplaceAll(s, "|", "\\|")
	if len(s) > 160 {
		cut := strings.LastIndex(s[:160], " ")
		if cut < 80 {
			cut = 160
		}
		s = s[:cut] + " …"
	}
	return s
}

var typeWord = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_\[\]]*$`)

// mermaidType turns a Postgres type into something Mermaid accepts as an
// attribute type (a single word). exact reports that the short form lost
// detail, so the caller puts the real type in the note.
func mermaidType(t string) (short string, exact bool) {
	replacer := strings.NewReplacer(
		"timestamp with time zone", "timestamptz",
		"timestamp without time zone", "timestamp",
		"time with time zone", "timetz",
		"time without time zone", "time",
		"character varying", "varchar",
		"double precision", "float8",
		"bit varying", "varbit",
		"character", "char",
	)
	s := replacer.Replace(t)
	if i := strings.Index(s, "("); i >= 0 {
		if j := strings.Index(s, ")"); j > i {
			s = s[:i] + s[j+1:]
		}
	}
	s = strings.ReplaceAll(s, " ", "_")
	s = strings.ReplaceAll(s, ".", "_")
	if !typeWord.MatchString(s) {
		s = "other"
	}
	return s, s != replacer.Replace(t) && s != t
}

func loadTables(ctx context.Context, conn *pgx.Conn) ([]*table, error) {
	rows, err := conn.Query(ctx, `
		SELECT n.nspname, c.relname, c.relkind::text,
		       coalesce(obj_description(c.oid, 'pg_class'), ''),
		       a.attname, format_type(a.atttypid, a.atttypmod), a.attnotnull, a.attnum,
		       EXISTS (SELECT 1 FROM pg_constraint k WHERE k.conrelid = c.oid AND k.contype = 'p' AND a.attnum = ANY (k.conkey)),
		       EXISTS (SELECT 1 FROM pg_constraint k WHERE k.conrelid = c.oid AND k.contype = 'f' AND a.attnum = ANY (k.conkey)),
		       EXISTS (SELECT 1 FROM pg_index i WHERE i.indrelid = c.oid AND i.indisunique AND i.indpred IS NULL
		                 AND i.indexprs IS NULL AND i.indnkeyatts = 1 AND i.indkey[0] = a.attnum)
		FROM pg_class c
		JOIN pg_namespace n ON n.oid = c.relnamespace
		JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
		WHERE n.nspname = ANY ($1) AND c.relkind IN ('r', 'p', 'v', 'm') AND NOT c.relispartition
		  -- PostGIS's own views (geometry_columns, ...) belong to the extension.
		  AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.classid = 'pg_class'::regclass
		                    AND d.objid = c.oid AND d.deptype = 'e')
		ORDER BY n.nspname = 'public' DESC, n.nspname, c.relname, a.attnum`, schemas)
	if err != nil {
		return nil, fmt.Errorf("read tables: %w", err)
	}
	defer rows.Close()
	var out []*table
	var cur *table
	for rows.Next() {
		var sch, name, kind, comment string
		c := &column{}
		if err := rows.Scan(&sch, &name, &kind, &comment, &c.name, &c.typ, &c.notNull, &c.position, &c.pk, &c.fk, &c.unique); err != nil {
			return nil, err
		}
		if skipTables[sch+"."+name] {
			continue
		}
		if cur == nil || cur.schema != sch || cur.name != name {
			cur = &table{schema: sch, name: name, kind: kind, comment: comment}
			out = append(out, cur)
		}
		cur.columns = append(cur.columns, c)
	}
	return out, rows.Err()
}

func loadForeignKeys(ctx context.Context, conn *pgx.Conn, tables []*table) ([]foreignKey, error) {
	rows, err := conn.Query(ctx, `
		SELECT k.conname,
		       cn.nspname || '.' || cc.relname, pn.nspname || '.' || pc.relname,
		       ARRAY(SELECT a.attname::text FROM unnest(k.conkey) WITH ORDINALITY u(n, o)
		             JOIN pg_attribute a ON a.attrelid = k.conrelid AND a.attnum = u.n ORDER BY u.o),
		       ARRAY(SELECT a.attname::text FROM unnest(k.confkey) WITH ORDINALITY u(n, o)
		             JOIN pg_attribute a ON a.attrelid = k.confrelid AND a.attnum = u.n ORDER BY u.o),
		       EXISTS (SELECT 1 FROM unnest(k.conkey) u(n) JOIN pg_attribute a
		                 ON a.attrelid = k.conrelid AND a.attnum = u.n WHERE NOT a.attnotnull),
		       EXISTS (SELECT 1 FROM pg_index i WHERE i.indrelid = k.conrelid AND i.indisunique
		                 AND i.indpred IS NULL AND i.indexprs IS NULL
		                 AND (i.indkey::int2[])[0:i.indnkeyatts - 1] @> k.conkey
		                 AND k.conkey @> (i.indkey::int2[])[0:i.indnkeyatts - 1])
		FROM pg_constraint k
		JOIN pg_class cc ON cc.oid = k.conrelid JOIN pg_namespace cn ON cn.oid = cc.relnamespace
		JOIN pg_class pc ON pc.oid = k.confrelid JOIN pg_namespace pn ON pn.oid = pc.relnamespace
		WHERE k.contype = 'f' AND cn.nspname = ANY ($1) AND pn.nspname = ANY ($1)
		  AND NOT cc.relispartition`, schemas)
	if err != nil {
		return nil, fmt.Errorf("read foreign keys: %w", err)
	}
	defer rows.Close()
	known := map[string]bool{}
	for _, t := range tables {
		known[t.qualified()] = true
	}
	var out []foreignKey
	for rows.Next() {
		var fk foreignKey
		if err := rows.Scan(&fk.name, &fk.child, &fk.parent, &fk.childCols, &fk.parentCols, &fk.nullable, &fk.oneToOne); err != nil {
			return nil, err
		}
		if known[fk.child] && known[fk.parent] {
			out = append(out, fk)
		}
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	sort.Slice(out, func(i, j int) bool {
		a, b := out[i], out[j]
		if a.parent != b.parent {
			return a.parent < b.parent
		}
		if a.child != b.child {
			return a.child < b.child
		}
		return strings.Join(a.childCols, ",") < strings.Join(b.childCols, ",")
	})
	return out, nil
}

// latestMigration names the highest migration applied, as its file name
// without .sql, e.g. 00030_onboarding_and_base_price_history.
func latestMigration(ctx context.Context, conn *pgx.Conn) (string, error) {
	var v int64
	if err := conn.QueryRow(ctx,
		`SELECT coalesce(max(version_id), 0) FROM goose_db_version WHERE is_applied AND version_id > 0`).Scan(&v); err != nil {
		return "", fmt.Errorf("read goose_db_version (were the migrations applied?): %w", err)
	}
	if v == 0 {
		return "", fmt.Errorf("no migration applied; run with -migrate against a scratch database")
	}
	prefix := fmt.Sprintf("%05d_", v)
	names, err := fs.Glob(migrations.FS, prefix+"*.sql")
	if err != nil || len(names) != 1 {
		return fmt.Sprintf("%05d", v), nil
	}
	return strings.TrimSuffix(names[0], ".sql"), nil
}
