/**
 * The VIEW MODELS: the shapes the screens read.
 *
 * This file used to claim to be the wire contract, generated-in-spirit from an
 * `openapi.yaml` that did not exist. Sprint 2 pointed the app at the real
 * server and that claim stopped being tenable, so the file changed jobs
 * instead of changing shape:
 *
 *   wire.ts      what `services/api` actually sends and accepts
 *   adapters.ts  the translation, in one place, with the reasons written down
 *   types.ts     this file — what a component is allowed to know about
 *
 * Keeping the two vocabularies apart is what let the API grow eight routes and
 * change three shapes mid-sprint without a single screen being edited. It also
 * means a field here is a PROMISE TO THE INTERFACE, not a description of a
 * payload: where the server has nothing to offer, the adapter fills in an
 * honest null and the comment says so, rather than the type quietly implying
 * the server knows something it does not.
 *
 * SPRINT 3 CLOSED THAT DEBT, and not the way this comment expected.
 * `services/api/openapi.yaml` exists now, and `wire.ts` was NOT replaced by
 * the generated module: `schema.ts` is generated from the spec and
 * `contract.assert.ts` makes the compiler check the two against each other,
 * field by field. The generated file is the judge; `wire.ts` stays the source,
 * because six thousand lines of `components["schemas"][...]` have nowhere to
 * put the reasons. This file stays either way, because these types are ours.
 *
 * Money is `…Cents` everywhere and is an integer. Dates that name a business
 * day are plain `YYYY-MM-DD` strings in the farm's timezone; instants are ISO
 * 8601 with an offset. Ids are UUIDv7 strings generated by whoever writes.
 */
import type { Geometry } from "../lib/geo";
import type { ApiErrorBody, DayISO, Instant, Uuid } from "./wire";

export type { ApiErrorBody, DayISO, Instant, Uuid };

/**
 * The server spells this `admin`. Everything on this side — the route guards,
 * the whole `permissions.ts` matrix, the Spanish strings — says
 * `administrator`, and `roleFromWire` is the two-line function that keeps both
 * true.
 */
export type Role = "owner" | "administrator" | "weigher";

/**
 * Derived from `suspendedAt`, which is the only farm lifecycle the API has.
 *
 * `"trial"` is gone. It was never a state the server could report — there is
 * no trial anywhere in the API and `trialDaysLeft` is documented as always
 * null — so the two screens that branched on it were branching on something
 * unreachable, and one of them would have printed "Prueba · null días" if it
 * ever had been reached.
 */
export type FarmStatus = "active" | "suspended";

/** Derived from `deletedAt`/`archivedAt`: the server has no status column. */
export type RecordStatus = "active" | "inactive";

/** The server's `contrato` / `tiempo` / `unidad_trabajo`. */
export type PayMode = "contract" | "time_unit" | "work_unit";

/**
 * Two values where the server has three. `explicit` and `activity_dated` both
 * mean "this price is already decided" and differ only in where the number
 * came from, which matters to the server and to nobody reading a screen.
 * `weekly_price` is the one a person has to know about, because it means the
 * figure in front of them is provisional until the week is priced.
 */
export type RateSource = "fixed" | "weekly_price";

/**
 * NOT a closed enum. Activity categories are a per-farm catalogue: RSP-011
 * says the selector comes "con opción de crear una nueva", and a farm that
 * also grows cacao will invent categories nobody planned for. The three below
 * are only what `seedFarm` puts in a new farm.
 */
export type ActivityCategory = string;
export const SEED_ACTIVITY_CATEGORIES = ["siembra", "mantenimiento", "cosecha"];

export type TimeUnit = "jornal" | "semanal" | "quincenal" | "mensual" | "custom";

export type LedgerKind =
  | "devengo"
  | "pago"
  | "anticipo"
  | "deduccion"
  | "ajuste"
  | "reverso";

export type PayMethod = "efectivo" | "transferencia" | "otro";

/* -- auth ------------------------------------------------------------ */

export interface Membership {
  farmId: Uuid;
  farmName: string;
  role: Role;
}

/**
 * Composed, not received. `POST /v1/auth/login` answers tokens and a farm
 * name; the user is a second call to `/v1/me`, which is why `api.login`
 * installs the tokens before it can finish building this.
 */
export interface Session {
  accessToken: string;
  refreshToken: string;
  /** Seconds. 900 — the access token is short on purpose. */
  expiresIn: number;
  user: MeUser;
}

/**
 * Where a membership stands. Three states and no fourth, because the fourth
 * everybody reaches for — "deleted" — is the one that must not exist: a
 * settlement names the user who wrote it, and a user id resolving to nothing
 * turns an audit trail into a list of UUIDs.
 *
 * `unknown` is not a state the server has; it is what this app shows when the
 * server sends something it does not recognise. It renders as "—", never as
 * "activo", because guessing that an unreadable membership is a working one is
 * the guess that opens a door.
 */
export type FarmUserStatus = "invited" | "active" | "revoked" | "unknown";

export interface FarmUser {
  id: Uuid;
  email: string;
  name: string;
  role: Role;
  status: FarmUserStatus;
  /**
   * THREE STATES, not two.
   *
   *   a date      they were last in then
   *   `null`      the server reports this and they have never been in
   *   `undefined` the server does not report it at all
   *
   * `/v1/users` is the third case today: the query behind it never selects a
   * last login. Collapsing that into `null` is what printed "Nunca ha entrado"
   * next to the owner while they were reading the screen. 1 January 1970 would
   * be a lie about a date; "nunca" is a lie about a person.
   */
  lastLoginAt?: string | null;
  createdAt: string | null;
  /**
   * The password the server minted for a newly invited person, returned once
   * by `POST /v1/users` and readable nowhere afterwards. Present only on the
   * result of an invitation; always absent from the list.
   */
  temporaryPassword?: string | null;
}

export interface FarmUserInput {
  id: Uuid;
  email: string;
  name: string;
  role: Role;
}

export interface MeUser {
  id: Uuid;
  email: string;
  name: string;
  role: Role;
  isSuperAdmin: boolean;
  farm: FarmSummary;
  /**
   * ALWAYS EMPTY from `/v1/me`, which describes the current farm only. The
   * list of a user's farms exists exactly once — in the 400 the login returns
   * when an address belongs to several — and is not readable afterwards.
   */
  memberships: Membership[];
}

export interface FarmSummary {
  id: Uuid;
  name: string;
  timezone: string;
  currency: string;
  status: FarmStatus;
  /** Always null: there is no trial in the API. The mock invented one. */
  trialDaysLeft: number | null;
  /** The standing price of a kilo. Null for a weigher, who may not see it. */
  priceCents?: number | null;
  areaHa?: number | null;
  city?: string | null;
  country?: string | null;
  phone?: string | null;
  address?: string | null;
}

export interface LoginRequest {
  email: string;
  password: string;
  farmId?: Uuid;
}

/**
 * A login that matched more than one farm. Arrives as a 400 with
 * `details.farms`, not as a success body, so `api.login` catches it and
 * returns this instead.
 */
export interface LoginChoice {
  choose: true;
  memberships: Membership[];
}

export interface SignupRequest {
  farm: {
    name: string;
    timezone: string;
    currency: string;
    /**
     * What a kilo is worth on day one. Required and positive: the server seeds
     * every new farm with a "Recoleccion" activity priced from it, so a farm
     * cannot exist without one.
     */
    priceCents: number;
  };
  owner: { email: string; name: string; password: string };
}

export interface SignupResponse {
  /**
   * Deliberately does NOT name the farm or the user. Signing up answers the
   * same thing whether or not the address already has an account, so that the
   * public route cannot be used to find out who is registered. The ids come
   * back from verify-email instead.
   */
  verificationEmailSentTo: string;
  /**
   * Only in development, where the server has no mail sender and echoes the
   * token instead. Null in production, where the owner uses the link in the
   * mail. The signup screen offers a one-click "confirmar y entrar" when this
   * is present, and tells the truth about why.
   */
  verificationToken: string | null;
}

/* -- catalogs -------------------------------------------------------- */

export interface CatalogItem {
  id: Uuid;
  name: string;
  /**
   * The server does NOT scope varieties to a crop type — the catalogue is
   * flat. Kept optional so the picker can group them the day it does.
   */
  cropTypeId?: Uuid;
}

/* -- plots ----------------------------------------------------------- */

/**
 * `PUT /v1/plots/{id}/boundary` answers `{plot, overlaps}` — NOT a plot.
 *
 * `overlaps` names the other lots this shape now runs into. It is a warning
 * and never a refusal: the server stores the polygon and says what it saw,
 * because two lots that touch are sometimes a slip of the mouse and sometimes
 * a terrace above a coffee lot, and only the owner knows which.
 *
 * `plot.crops` is EMPTY here: the handler returns the plot's own columns
 * without re-joining what is planted in it.
 */
export interface BoundaryResult {
  plot: Plot;
  overlaps: CatalogItem[];
}

export interface PlotCrop {
  id: Uuid;
  cropTypeId: Uuid;
  cropTypeName: string;
  varietyId: Uuid | null;
  varietyName: string | null;
  areaHa: number | null;
  plantedAt: DayISO | null;
}

export interface Plot {
  id: Uuid;
  name: string;
  department: string;
  municipality: string;
  /**
   * What the owner declared, and NULL when they declared nothing.
   *
   * The adapter used to write `p.areaHa ?? 0`, which turned an unknown area
   * into "0,00 ha" on the list and on the lot's own file — and then added that
   * zero into the farm's declared total, understating it with no sign that
   * anything was missing. `AreaComparison` has always accepted a null here;
   * the `?? 0` was destroying a distinction the components downstream were
   * already built to show.
   */
  areaHa: number | null;
  /**
   * What PostGIS measured of the drawn polygon. Null until one is drawn. Both
   * figures are returned and both are shown: they always disagree, and
   * choosing one for the owner is deciding which of them lies.
   */
  computedAreaHa: number | null;
  /**
   * GeoJSON geometry, straight from the server, and deliberately `unknown`.
   *
   * Nothing on the wire is checked, so a screen that types this as a Polygon
   * is asserting something no code verified. `asGeometry` in `lib/geo.ts` is
   * the one door in: it either hands back a geometry or a null, and the map
   * draws nothing rather than drawing `undefined`.
   */
  boundary: unknown | null;
  crops: PlotCrop[];
  status: RecordStatus;
}

export interface PlotInput {
  id: Uuid;
  name: string;
  department: string;
  municipality: string;
  areaHa: number;
  /**
   * The shape drawn on the map, as a GeoJSON Polygon, or absent when the form
   * never opened the map. ABSENT AND NULL MEAN THE SAME THING to the server
   * (`hasBoundary` treats a null as "not sent"), which is deliberate: an edit
   * to a plot's name must not be able to erase a polygon by omission.
   */
  boundary?: Geometry | null;
  crops: Array<{
    id: Uuid;
    cropTypeId: Uuid;
    varietyId: Uuid | null;
    areaHa: number | null;
    plantedAt: DayISO | null;
  }>;
}

/* -- workers --------------------------------------------------------- */

export type DocumentType = "CC" | "CE" | "TI" | "PPT" | "PAS";

export interface Worker {
  id: Uuid;
  name: string;
  lastName: string;
  documentType: DocumentType;
  /** `docId` on the wire; this is the phrase on the identity card. */
  documentNumber: string;
  /** The number painted on the basket, for the scale. */
  tag: string | null;
  phone: string | null;
  address: string | null;
  city: string | null;
  country: string | null;
  /**
   * ALWAYS NULL. `photoId` points into a media store that does not exist yet,
   * so there is no URL to build and the avatar falls back to an initial —
   * which is honest about there being no photo.
   */
  photoUrl: string | null;
  /**
   * ALWAYS NULL. The server records when the ROW was created, which is not
   * when the person started working, and reporting one as the other would put
   * a wrong date on a profile.
   */
  startedAt: DayISO | null;
  status: RecordStatus;
  /** Present only where a balance was joined in; never on a plain list. */
  balanceCents?: number;
}

export interface WorkerInput {
  id: Uuid;
  name: string;
  lastName: string;
  documentType: DocumentType;
  documentNumber: string;
  tag?: string | null;
  phone: string;
  address?: string;
  city?: string;
  country?: string;
  /** Accepted by the form and DROPPED: there is no media store yet. */
  photoDataUrl?: string | null;
  /** Accepted by the form and DROPPED: there is no such column. */
  startedAt?: DayISO;
}

export interface Balance {
  workerId: Uuid;
  earnedCents: number;
  paidCents: number;
  deductedCents: number;
  /** Derived from the ledger on every read. Never a stored total. */
  balanceCents: number;
  /** A DAY, not an instant: the ledger is keyed by local day. */
  lastMovementOn: DayISO | null;
  /**
   * False for somebody who has left the payroll and is still owed money. They
   * remain in `/v1/balances` precisely so the debt does not vanish with them.
   */
  active: boolean;
}

export interface LedgerEntry {
  id: Uuid;
  workerId: Uuid;
  kind: LedgerKind;
  /** Composed from the note and the kind: there is no `concept` column. */
  concept: string;
  /** Signed. `devengo` positive; `pago`, `anticipo`, `deduccion` negative. */
  amountCents: number;
  date: DayISO;
  method: PayMethod | null;
  /** ALWAYS NULL: the API issues no receipt numbers. */
  receiptNumber: string | null;
  reversesId: Uuid | null;
  /** Set on the `devengo` a settlement wrote. */
  settlementId?: Uuid | null;
}

export interface WorkerNote {
  id: Uuid;
  text: string;
  date: DayISO;
  /**
   * ALWAYS EMPTY. The server sends `createdBy` as a user id and there is no
   * users route to resolve it, and a UUID where a person's name belongs is
   * worse than a blank.
   */
  authorName: string;
}

export interface WorkerProfile {
  worker: Worker;
  balance: Balance;
  workRecords: WorkRecord[];
  /**
   * Sum of the work no live settlement has claimed yet, and NULL when
   * `/v1/workers/{id}/payables` could not be reached.
   *
   * It used to be `payables?.grossCents ?? 0`. With that request down, an
   * employee owed $868.000 read "Pendiente de liquidar $0" and the detail
   * block below it disappeared entirely — a screen that looks like a person
   * who is square with the farm, produced by a failed GET. Null has no
   * rendering that could be mistaken for a figure.
   */
  pendingCents: number | null;
  ledger: LedgerEntry[];
  /**
   * AT MOST HOW MANY ENTRIES THIS SCREEN ASKED FOR.
   *
   * `/v1/workers/{id}/profile` cuts the ledger at `?limit` and answers with
   * the page without saying anywhere that it cut it. A table headed
   * "Historial financiero" that is really the last fifty entries, and does not
   * say so, belongs to the same family as the rest of the audit's findings: a
   * screen claiming more than it knows.
   *
   * With the cap here, the screen can compare `ledger.length` against it and
   * say so. And asking for it explicitly instead of inheriting the server's
   * `default` means the number on screen is the number that was requested.
   */
  ledgerLimit: number;
  notes: WorkerNote[];
}

/* -- activities ------------------------------------------------------ */

export interface ActivityRate {
  /** Prices have history: a work record freezes the one in force on its date. */
  validFrom: DayISO;
  rateCents: number;
}

export interface Activity {
  id: Uuid;
  name: string;
  category: ActivityCategory;
  payMode: PayMode;
  /** work_unit only: kg, arroba, canasta... Resolved from `unitId`. */
  workUnit: string | null;
  /** time_unit only. Lives on the RATE server-side, not on the activity. */
  timeUnit: TimeUnit | null;
  customQty: number | null;
  customPeriod: "dia" | "mes" | "ano" | null;
  rateSource: RateSource;
  /**
   * UNDEFINED rather than zero when there is no rate — which happens both for
   * a weigher, who may never see one, and for anybody asking about a date
   * before the activity had a price. A zero would render as "$0", which is a
   * claim about the price rather than an absence of one.
   */
  defaultRateCents?: number;
  rates?: ActivityRate[];
  status: RecordStatus;
}

export interface ActivityInput {
  id: Uuid;
  name: string;
  category: ActivityCategory;
  payMode: PayMode;
  workUnit?: string | null;
  timeUnit?: TimeUnit | null;
  rateSource: RateSource;
  defaultRateCents?: number | null;
  validFrom?: DayISO;
}

/* -- work records (labores) ------------------------------------------ */

/**
 * Every human-readable string on this type is resolved client-side from
 * `refs.ts`. The server sends five ids and a quantity and no names at all —
 * see the note at the top of `adapters.ts` for why that is right rather than
 * miserly. An id that resolves to nothing becomes "—", never a blank.
 */
export interface WorkRecord {
  id: Uuid;
  workerId: Uuid;
  workerName: string;
  activityId: Uuid;
  activityName: string;
  category: ActivityCategory;
  payMode: PayMode;
  unitLabel: string | null;
  plotIds: Uuid[];
  plotNames: string[];
  plotCropIds: Uuid[];
  plotCropNames: string[];
  dateFrom: DayISO;
  dateTo: DayISO;
  quantity: number;
  /**
   * Null while the price is not frozen yet: work_unit + weekly_price freezes
   * at settlement time, everything else freezes on write.
   */
  rateCents: number | null;
  /** What it is worth today. Not a ledger entry until it is settled. */
  estimatedAmountCents: number;
  /**
   * False once a settlement froze the amount, true while it still comes from
   * the week's price and could move if that price changes. What the farm owes
   * and what it has paid must not look alike on a screen.
   */
  amountIsEstimate: boolean;
  note: string | null;
  settled: boolean;
  status: RecordStatus;
}

export interface WorkRecordInput {
  id: Uuid;
  workerId: Uuid;
  activityId: Uuid;
  plotIds: Uuid[];
  plotCropIds: Uuid[];
  dateFrom: DayISO;
  dateTo: DayISO;
  quantity: number;
  rateCents?: number | null;
  note?: string;
}

/* -- money ----------------------------------------------------------- */

/**
 * One line of what is owed: a work record seen from the settlement's side.
 *
 * `rateCents` and `weekStart` are here for one reason — `api/grossChange.ts`
 * compares two of these lists to work out WHY a gross moved between the moment
 * somebody read it and the moment they approved it. Without the rate, a week
 * whose price changed is indistinguishable from a week whose weighings
 * changed, and the difference screen can only say "the number is different".
 */
export interface PayableLine {
  id: Uuid;
  activityName: string;
  dateFrom: DayISO;
  dateTo: DayISO;
  /** The Monday the payable belongs to. What a weekly price is keyed on. */
  weekStart: DayISO;
  /** Empty: a payable carries the activity and the money, not the plots. */
  plotNames: string[];
  quantity: number;
  /** Non-null only for work paid by weighed quantity — a *pesada*. */
  unitLabel: string | null;
  /**
   * Resolved by the server even when the record itself has no frozen price:
   * a `weekly_price` payable is priced at settlement time, which is exactly
   * the value that can move underneath an open payment screen.
   */
  rateCents: number;
  /**
   * `weekly_price` means THIS ROW IS NOT DECIDED YET: it is priced at
   * settlement time from the week's price, so the amount below is what it
   * would be worth today and not what anybody owes. Everything else is frozen.
   *
   * The screens show the difference. What the farm owes and what it might owe
   * must not look alike in a column of pesos — and it is the same rows that
   * move underneath an open payment screen, which is why the guard in
   * `grossChange.ts` and this flag describe the same fact from two sides.
   */
  rateSource: RateSource;
  amountCents: number;
}

export interface Payables {
  workRecords: PayableLine[];
  /**
   * FOR DISPLAY ONLY. These advances and deductions are already inside
   * `balanceCents`; subtracting them again charges the worker twice for the
   * same debt.
   */
  debts: Array<{ id: Uuid; concept: string; date: DayISO; amountCents: number }>;
  /** The unsettled work above. */
  grossCents: number;
  /** What the ledger already says, advances and deductions included. */
  balanceCents: number;
  /** `balanceCents + grossCents`: what the farm owes if all of it settles now. */
  totalCents: number;
}

export interface PaymentInput {
  id: Uuid;
  workerId: Uuid;
  amountCents: number;
  method: PayMethod;
  note?: string;
  /**
   * Work records to settle before paying. Empty means "against the balance
   * alone". Settling is a separate write; see `api.createPayment`.
   */
  payableIds?: Uuid[];
  /**
   * The gross the user SAW and approved, in cents. Required whenever
   * `payableIds` is non-empty — `createPayment` throws without it rather than
   * settling whatever the server happens to hold at the moment of the write.
   * See the note on `api.settle`.
   */
  expectedGrossCents?: number;
  /**
   * The lines that made up that gross. Not needed for the guard, which is
   * arithmetic on one number; needed to say WHY the figure moved when the
   * guard fires, which is the difference between a refusal and an explanation.
   */
  expectedLines?: PayableLine[];
  /**
   * The id for the settlement that `createPayment` writes before the payment
   * itself, minted by the caller at the moment the figure was approved and
   * reused by every retry of that same approval. Without it the settlement
   * gets a fresh id per attempt and the server's idempotency — which is what
   * makes a retry safe — never gets the chance to fire. See `lib/writeOnce.ts`.
   */
  settlementId?: Uuid;
}

/* -- settlements ----------------------------------------------------- */

/**
 * A settlement as the farm's list shows it: who, which weeks, how much, and
 * whether it still stands.
 *
 * `status` has two values and no third. A void settlement is never reopened —
 * `docs/sincronizacion.md`: "Ninguna liquidación cerrada se reabre nunca, por
 * ningún motivo" — so there is no "reversed to draft" state to model, and the
 * screen offers no control that would imply one.
 */
export interface SettlementSummary {
  id: Uuid;
  workerId: Uuid;
  /** Joined from the worker list. "—" when the id resolves to nothing. */
  workerName: string;
  /**
   * The period ACTUALLY covered — the Monday of the earliest payable taken in
   * — not the window the caller asked over. A settlement asked for "everything
   * outstanding" would otherwise be filed under 1970.
   */
  periodStart: DayISO;
  periodEnd: DayISO;
  grossCents: number;
  status: "open" | "void";
  /** How many payables it froze. Shown so a row's weight is visible at once. */
  lineCount: number;
  note: string | null;
  createdAt: string;
  voidedAt: string | null;
}

/**
 * The list of settlements, WITH ITS HOLES.
 *
 * Without `GET /v1/settlements` the list is assembled by reading every
 * employee's ledger, and those reads can fail one at a time. Returning only
 * the array left the screen with no way of telling "this farm has settled
 * nothing" apart from "I could not read the ledgers" — and it asserted the
 * first, with a blank payroll sheet behind it.
 *
 * Both counters are zero when the collection route answered, which is the
 * case where there is no fan-out and no holes to declare.
 */
export interface SettlementList {
  items: SettlementSummary[];
  /** Employees whose ledger could not be read: their settlements are missing. */
  unreadableLedgers: number;
  /** Settlements found in a ledger that then could not be read. */
  unreadableSettlements: number;
}

export interface Settlement extends SettlementSummary {
  /** The frozen lines: what was settled, at the price it was settled at. */
  lines: PayableLine[];
  /** Lines the server marks voided. Normally empty unless the whole is void. */
  voidedLineIds: Uuid[];
}

export interface Payment {
  id: Uuid;
  workerId: Uuid;
  /** Positive: what was handed over. The ledger stores it negative. */
  amountCents: number;
  method: PayMethod;
  /**
   * The movement id written for a person — `3F7A-91C2` — because the API
   * issues no receipt numbers and a 36-character UUID is not something anybody
   * dictates over the phone. The whole id is `id`, above; it does not go on
   * the paper. See `lib/receipt.ts`.
   */
  receiptNumber: string;
  balanceBeforeCents: number;
  balanceAfterCents: number;
  date: DayISO;
}

export interface DeductionInput {
  id: Uuid;
  workerId: Uuid;
  amountCents: number;
  concept: string;
  date: DayISO;
}

/* -- weekly price ---------------------------------------------------- */

export interface WeekPrice {
  monday: DayISO;
  costPerUnitCents: number;
}

/* -- super-admin ----------------------------------------------------- */

export interface AdminFarm {
  id: Uuid;
  name: string;
  /**
   * ALWAYS EMPTY. The console may not read a farm's users — the projection is
   * the enforcement of what a platform administrator can know.
   */
  ownerEmail: string;
  status: FarmStatus;
  createdAt: Instant;
  /** ALWAYS NULL: nothing records a last access. */
  lastAccessAt: Instant | null;
  /** NULL: the console may not read employees, so it cannot count them. */
  workerCount: number | null;
  city?: string | null;
  country?: string | null;
}

/* -- envelopes ------------------------------------------------------- */

/** Lists come back as `{items}`. There is no `total` and no pagination. */
export interface Page<T> {
  items: T[];
}

/* ------------------------------------------------------------------ */
/* Products, inventory, sales and expenses  (RSP-018 … RSP-033)        */
/* ------------------------------------------------------------------ */

/**
 * TWO RULES OF THE DESIGN ARE ENCODED IN THESE TYPES, not left to a comment
 * on a form somewhere.
 *
 * 1. EXISTENCIAS ARE DERIVED. `Product.stock` is readonly-by-construction:
 *    there is no `ProductInput.stock`, no `updateStock`, and nothing anywhere
 *    in this app that sends a quantity as a state. The only way a number moves
 *    is `StockMoveInput`, which appends a fact. This mirrors the ledger
 *    exactly — a balance is summed from movements on every read — and it is
 *    the same argument: a stored total is a number that eventually disagrees
 *    with the facts underneath it, and on that day nothing in the system can
 *    say which of the two is right.
 *
 * 2. AN EXPENSE HAS EXACTLY ONE TARGET. `ExpenseInput` is a discriminated
 *    union on `target`, so "charged to both" and "charged to neither" are not
 *    values this type can hold. The database says the same thing with
 *    `expense_target`; making it unrepresentable here means the form cannot
 *    submit one, rather than being told off after it tried.
 */

/** The seven values of `stock_reason`. A closed enum: the code branches on it. */
export type StockReason =
  | "cosecha"
  | "compra"
  | "venta"
  | "consumo"
  | "merma"
  | "traslado"
  | "ajuste";

/** Which way a reason moves the quantity. `stock_sign` in the database. */
export const STOCK_REASON_SIGN: Record<StockReason, "in" | "out" | "either"> = {
  cosecha: "in",
  compra: "in",
  venta: "out",
  consumo: "out",
  merma: "out",
  traslado: "either",
  ajuste: "either",
};

/** What a person calls each one. */
export const STOCK_REASON_LABEL: Record<StockReason, string> = {
  cosecha: "Cosecha",
  compra: "Compra",
  venta: "Venta",
  consumo: "Consumo",
  merma: "Merma",
  traslado: "Traslado",
  ajuste: "Ajuste",
};

export interface Product {
  id: Uuid;
  name: string;
  categoryId: Uuid | null;
  categoryName: string | null;
  storageUnitId: Uuid;
  /** "Bulto", "Kilo" — what the quantity is counted in. */
  storageUnit: string;
  note: string | null;
  /**
   * DERIVED, across every warehouse. There is no route that sets it and no
   * field on `ProductInput` that carries it: the way this number changes is a
   * movement.
   */
  stock: number;
  status: RecordStatus;
}

export interface ProductInput {
  id: Uuid;
  name: string;
  /** By name: a category the farm has not used yet is created, not rejected. */
  categoryName?: string | null;
  categoryId?: Uuid | null;
  storageUnit?: string;
  storageUnitId?: Uuid | null;
  note?: string | null;
}

export interface Customer {
  id: Uuid;
  name: string;
  documentType: string | null;
  documentNumber: string | null;
  phone: string | null;
  status: RecordStatus;
}

export interface StockMove {
  id: Uuid;
  productId: Uuid;
  productName: string;
  warehouseId: Uuid;
  warehouseName: string;
  plotId: Uuid | null;
  plotName: string | null;
  plotCropId: Uuid | null;
  /** Signed: positive comes in, negative goes out. */
  qty: number;
  reason: StockReason;
  note: string | null;
  /** Set when the movement belongs to a sale. */
  saleId: Uuid | null;
  /** Set on a movement that undoes another. */
  reversesId: Uuid | null;
  /** Set on a movement somebody has already undone. */
  reversedById: Uuid | null;
  date: DayISO;
  /** The sticker batch printed for this movement, if any. RSP-025. */
  labelBatchId: Uuid | null;
}

export interface StockMoveInput {
  id: Uuid;
  productId: Uuid;
  /**
   * REQUIRED by the contract. A warehouse is not created on the fly here the
   * way a category is: `POST /v1/warehouses` is its own call, and the picker
   * makes it before the movement, so a typo cannot invent a shed mid-write.
   */
  warehouseId: Uuid;
  plotId?: Uuid | null;
  plotCropId?: Uuid | null;
  /**
   * SIGNED, and the sign has to agree with the reason. The form asks for a
   * positive number and applies the sign from the reason, so nobody has to
   * think about it — see `signedQty`.
   */
  qty: number;
  reason: StockReason;
  note?: string | null;
  /** Absent means "today in the farm's timezone", decided by the database. */
  date?: DayISO;
  /** How many identification stickers to generate. RSP-025. */
  labels?: number;
  /** Record an outgoing movement that takes the level below zero. */
  allowNegative?: boolean;
}

/** One line of the existencias screen: a product in a warehouse. A SUM. */
export interface StockLevel {
  productId: Uuid;
  productName: string;
  storageUnit: string;
  warehouseId: Uuid;
  warehouseName: string;
  qty: number;
}

export interface Label {
  code: string;
  productName: string;
  storageUnit: string;
  qty: number;
  warehouseName: string;
  plotName: string | null;
  date: DayISO;
}

/**
 * RSP-025 says the system prints the stickers. There is no printer on a
 * server, so what it does is generate the batch and give it an id; printing is
 * the browser's job. Doing it the other way round would make receiving a
 * truckload of coffee fail because a printer was out of paper.
 */
export interface LabelBatch {
  id: Uuid;
  stockMoveId: Uuid;
  count: number;
  labels: Label[];
}

export interface Sale {
  id: Uuid;
  productId: Uuid;
  productName: string;
  storageUnit: string;
  customerId: Uuid | null;
  customerName: string | null;
  warehouseId: Uuid;
  warehouseName: string;
  quantity: number;
  amountCents: number;
  note: string | null;
  date: DayISO;
  /** The outgoing movement this sale wrote. */
  stockMoveId: Uuid | null;
  /** True once it has been voided. Voiding reverses, it never deletes. */
  voided: boolean;
}

export interface SaleInput {
  id: Uuid;
  productId: Uuid;
  customerId?: Uuid | null;
  /** Or by name: "Cooperativa" typed into the picker creates the customer. */
  customerName?: string;
  /** Required: a sale takes the product out of somewhere. */
  warehouseId: Uuid;
  quantity: number;
  amountCents: number;
  note?: string | null;
  date: DayISO;
  /**
   * "Yes, I know the warehouse says there is not that much." Without it the
   * server answers 409 INSUFFICIENT_STOCK. The same shape as
   * `allowOverpayment` on a payment, and for the same reason: the guard exists
   * because the web is a keyboard, and the override exists because the
   * warehouse is not always in the database before the truck leaves.
   */
  allowNegativeStock?: boolean;
}

/** RSP-031's "Tipo de gasto": an activity, or a lot and its crop. Never both. */
export type ExpenseTarget = "activity" | "plot";

export interface Expense {
  id: Uuid;
  concept: string;
  amountCents: number;
  date: DayISO;
  target: ExpenseTarget;
  activityId: Uuid | null;
  activityName: string | null;
  plotId: Uuid | null;
  plotName: string | null;
  plotCropId: Uuid | null;
  cropName: string | null;
  note: string | null;
  status: RecordStatus;
}

/**
 * A union, not an object with four optional ids.
 *
 * `expense_target` in the database is
 * `(activity_id IS NOT NULL) + (coalesce(plot_id, plot_crop_id) IS NOT NULL) = 1`.
 * Written as a union here, "charged to both" and "charged to neither" are
 * shapes the form CANNOT construct — so the constraint is a compile error
 * rather than a 400 after somebody has typed the whole thing in.
 */
export type ExpenseInput =
  | {
      id: Uuid;
      concept: string;
      amountCents: number;
      date: DayISO;
      target: "activity";
      activityId: Uuid;
      note?: string | null;
    }
  | {
      id: Uuid;
      concept: string;
      amountCents: number;
      date: DayISO;
      target: "plot";
      plotId: Uuid;
      /** Optional: a lot may have several crops and a cost may cover them all. */
      plotCropId?: Uuid | null;
      note?: string | null;
    };

/**
 * `GET /v1/sales` answers the rows AND the totals of the LIVE ones.
 *
 * Summed by the server, not here: a total added up in the browser is the total
 * of whatever page happened to load, and a voided sale would have to be
 * excluded correctly by every caller instead of once.
 */
export interface SaleList {
  items: Sale[];
  totalCents: number;
  totalQty: number;
}

/** `GET /v1/expenses` answers the rows AND their sum, in one envelope. */
export interface ExpenseList {
  items: Expense[];
  count: number;
  totalCents: number;
}
