/**
 * Wire types for the REST contract of `docs/arquitectura-api.md`.
 *
 * TEMPORARY, AND DELIBERATELY SO. The contract says `openapi.yaml` in
 * `packages/shared` is the source of truth and that these types are generated
 * with `openapi-typescript`, with CI failing on a diff. That package is being
 * written in parallel and does not exist yet, so this file stands in for the
 * generated one. It is shaped exactly like the generated output (one flat
 * module of interfaces, no logic, no imports) precisely so that deleting it
 * and pointing the imports at the generated module is a one-line change and
 * not a refactor.
 *
 * Money is `…Cents` everywhere and is an integer. Dates that name a business
 * day are plain `YYYY-MM-DD` strings in the farm's timezone; instants are ISO
 * 8601 with an offset. Ids are UUIDv7 strings generated by whoever writes.
 */

export type Uuid = string;
/** YYYY-MM-DD in the farm's timezone. */
export type DayISO = string;
/** Full ISO 8601 instant. */
export type Instant = string;

export type Role = "owner" | "administrator" | "weigher";
export type FarmStatus = "trial" | "active" | "suspended";
export type RecordStatus = "active" | "inactive";

export type PayMode = "contract" | "time_unit" | "work_unit";
export type RateSource = "fixed" | "weekly_price";
/**
 * NOT a closed enum. `docs/decisiones.md` (equipo, 2026-08-29) makes activity
 * categories a per-farm catalogue: RSP-011 says the selector comes "con opción
 * de crear una nueva", and a farm that also grows cacao will invent categories
 * nobody planned for. The three below are only the seed.
 */
export type ActivityCategory = string;
export const SEED_ACTIVITY_CATEGORIES = ["siembra", "mantenimiento", "cosecha"];
export type TimeUnit = "jornal" | "semanal" | "quincenal" | "mensual" | "custom";
export type LedgerKind =
  | "devengo"
  | "pago"
  | "anticipo"
  | "deduccion"
  | "ajuste"
  | "reverso";
export type PayMethod = "efectivo" | "transferencia" | "otro";

/* -- auth ------------------------------------------------------------ */

export interface Membership {
  farmId: Uuid;
  farmName: string;
  role: Role;
}

export interface Session {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
  user: MeUser;
}

export interface MeUser {
  id: Uuid;
  email: string;
  name: string;
  role: Role;
  isSuperAdmin: boolean;
  farm: FarmSummary;
  memberships: Membership[];
}

export interface FarmSummary {
  id: Uuid;
  name: string;
  timezone: string;
  currency: string;
  status: FarmStatus;
  /** Days left when status is "trial". Null otherwise. */
  trialDaysLeft: number | null;
}

export interface LoginRequest {
  email: string;
  password: string;
  farmId?: Uuid;
}

/** A login that matched more than one membership: the user has to choose. */
export interface LoginChoice {
  choose: true;
  memberships: Membership[];
}

export interface SignupRequest {
  farm: { name: string; timezone: string; department: string; municipality: string };
  owner: { email: string; name: string; password: string };
}

export interface SignupResponse {
  farmId: Uuid;
  /** The farm is not usable until the owner clicks the link in this mail. */
  verificationEmailSentTo: string;
}

/* -- catalogs -------------------------------------------------------- */

export interface CatalogItem {
  id: Uuid;
  name: string;
  /** Varieties are scoped to a crop type. */
  cropTypeId?: Uuid;
}

/* -- plots ----------------------------------------------------------- */

export interface PlotCrop {
  id: Uuid;
  cropTypeId: Uuid;
  cropTypeName: string;
  varietyId: Uuid | null;
  varietyName: string | null;
  areaHa: number | null;
  plantedAt: DayISO | null;
}

export interface Plot {
  id: Uuid;
  name: string;
  department: string;
  municipality: string;
  /** What the owner declared. */
  areaHa: number;
  /**
   * What ST_Area says about the drawn polygon. Null until Sprint 2 draws one.
   * Both figures are returned and both are shown: they always disagree and
   * choosing one for the owner is deciding which of them lies.
   */
  computedAreaHa: number | null;
  boundary: unknown | null;
  crops: PlotCrop[];
  status: RecordStatus;
}

export interface PlotInput {
  id: Uuid;
  name: string;
  department: string;
  municipality: string;
  areaHa: number;
  crops: Array<{
    id: Uuid;
    cropTypeId: Uuid;
    varietyId: Uuid | null;
    areaHa: number | null;
    plantedAt: DayISO | null;
  }>;
}

/* -- workers --------------------------------------------------------- */

export type DocumentType = "CC" | "CE" | "TI" | "PPT" | "PAS";

export interface Worker {
  id: Uuid;
  name: string;
  lastName: string;
  documentType: DocumentType;
  documentNumber: string;
  phone: string | null;
  address: string | null;
  city: string | null;
  country: string | null;
  photoUrl: string | null;
  startedAt: DayISO | null;
  status: RecordStatus;
  /** Absent for the weigher: their token gets a narrower projection. */
  balanceCents?: number;
}

export interface WorkerInput {
  id: Uuid;
  name: string;
  lastName: string;
  documentType: DocumentType;
  documentNumber: string;
  phone: string;
  address?: string;
  city?: string;
  country?: string;
  photoDataUrl?: string | null;
  startedAt?: DayISO;
}

export interface Balance {
  workerId: Uuid;
  earnedCents: number;
  paidCents: number;
  deductedCents: number;
  /** Derived from the ledger on every read. Never a stored total. */
  balanceCents: number;
  lastMovementAt: Instant | null;
}

export interface LedgerEntry {
  id: Uuid;
  workerId: Uuid;
  kind: LedgerKind;
  concept: string;
  /** Signed. devengo positive; pago, anticipo and deduccion negative. */
  amountCents: number;
  date: DayISO;
  method: PayMethod | null;
  receiptNumber: string | null;
  reversesId: Uuid | null;
}

export interface WorkerNote {
  id: Uuid;
  text: string;
  date: DayISO;
  authorName: string;
}

export interface WorkerProfile {
  worker: Worker;
  balance: Balance;
  workRecords: WorkRecord[];
  /** Sum of the work records no live settlement has claimed yet. */
  pendingCents: number;
  ledger: LedgerEntry[];
  notes: WorkerNote[];
}

/* -- activities ------------------------------------------------------ */

export interface ActivityRate {
  /** Prices have history: a work record freezes the one in force on its date. */
  validFrom: DayISO;
  rateCents: number;
}

export interface Activity {
  id: Uuid;
  name: string;
  category: ActivityCategory;
  payMode: PayMode;
  /** work_unit only: kg, arroba, canasta... */
  workUnit: string | null;
  /** time_unit only. */
  timeUnit: TimeUnit | null;
  customQty: number | null;
  customPeriod: "dia" | "mes" | "ano" | null;
  rateSource: RateSource;
  /** Withheld from the weigher's projection. */
  defaultRateCents?: number;
  rates?: ActivityRate[];
  status: RecordStatus;
}

export interface ActivityInput {
  id: Uuid;
  name: string;
  category: ActivityCategory;
  payMode: PayMode;
  workUnit?: string | null;
  timeUnit?: TimeUnit | null;
  rateSource: RateSource;
  defaultRateCents?: number | null;
  validFrom?: DayISO;
}

/* -- work records (labores) ------------------------------------------ */

export interface WorkRecord {
  id: Uuid;
  workerId: Uuid;
  workerName: string;
  activityId: Uuid;
  activityName: string;
  category: ActivityCategory;
  payMode: PayMode;
  unitLabel: string | null;
  plotIds: Uuid[];
  plotNames: string[];
  plotCropIds: Uuid[];
  plotCropNames: string[];
  dateFrom: DayISO;
  dateTo: DayISO;
  quantity: number;
  /**
   * Null while the price is not frozen yet: work_unit + weekly_price freezes
   * at settlement time, everything else freezes on write.
   */
  rateCents: number | null;
  /** What it is worth today. Not a ledger entry until it is settled. */
  estimatedAmountCents: number;
  note: string | null;
  settled: boolean;
  status: RecordStatus;
}

export interface WorkRecordInput {
  id: Uuid;
  workerId: Uuid;
  activityId: Uuid;
  plotIds: Uuid[];
  plotCropIds: Uuid[];
  dateFrom: DayISO;
  dateTo: DayISO;
  quantity: number;
  rateCents?: number | null;
  note?: string;
}

/* -- money ----------------------------------------------------------- */

export interface Payables {
  workRecords: Array<{
    id: Uuid;
    activityName: string;
    dateFrom: DayISO;
    dateTo: DayISO;
    plotNames: string[];
    quantity: number;
    unitLabel: string | null;
    amountCents: number;
  }>;
  debts: Array<{ id: Uuid; concept: string; date: DayISO; amountCents: number }>;
  totalCents: number;
}

export interface PaymentInput {
  id: Uuid;
  workerId: Uuid;
  amountCents: number;
  method: PayMethod;
  note?: string;
  /** Work records this payment settles. Empty means "against the balance". */
  payableIds?: Uuid[];
}

export interface Payment {
  id: Uuid;
  workerId: Uuid;
  amountCents: number;
  method: PayMethod;
  receiptNumber: string;
  balanceBeforeCents: number;
  balanceAfterCents: number;
  date: DayISO;
}

export interface DeductionInput {
  id: Uuid;
  workerId: Uuid;
  amountCents: number;
  concept: string;
  date: DayISO;
}

/* -- weekly price ---------------------------------------------------- */

export interface WeekPrice {
  monday: DayISO;
  costPerUnitCents: number;
}

/* -- super-admin ----------------------------------------------------- */

export interface AdminFarm {
  id: Uuid;
  name: string;
  ownerEmail: string;
  status: FarmStatus;
  createdAt: Instant;
  lastAccessAt: Instant | null;
  workerCount: number;
}

/* -- envelopes ------------------------------------------------------- */

export interface Page<T> {
  items: T[];
  total: number;
}

export interface ApiErrorBody {
  error: {
    code: string;
    message: string;
    details?: Record<string, unknown>;
  };
}
